// Code generated by pigeon (https://github.com/PuerkitoBio/pigeon)
// on 2015-05-06 20:24:23.706076707 -0400 EDT

package main

import (
	"bytes"
	"errors"
	"fmt"
	"io"
	"io/ioutil"
	"os"
	"strconv"
	"unicode"
	"unicode/utf8"

	"github.com/PuerkitoBio/pigeon/ast"
)

func (c *current) onGrammar1(initializer, rules interface{}) (interface{}, error) {
	pos := c.astPos()

	// create the grammar, assign its initializer
	g := ast.NewGrammar(pos)
	initSlice := toIfaceSlice(initializer)
	if len(initSlice) > 0 {
		g.Init = initSlice[0].(*ast.CodeBlock)
	}

	rulesSlice := toIfaceSlice(rules)
	g.Rules = make([]*ast.Rule, len(rulesSlice))
	for i, duo := range rulesSlice {
		g.Rules[i] = duo.([]interface{})[0].(*ast.Rule)
	}

	return g, nil
}

func (v *ϡvm) callOnGrammar1() (interface{}, error) {
	stack := v.a.peek()
	return v.cur.onGrammar1(stack["initializer"], stack["rules"])
}

func (c *current) onInitializer1(code interface{}) (interface{}, error) {
	return code, nil
}

func (v *ϡvm) callOnInitializer1() (interface{}, error) {
	stack := v.a.peek()
	return v.cur.onInitializer1(stack["code"])
}

func (c *current) onRule1(name, display, expr interface{}) (interface{}, error) {
	pos := c.astPos()

	rule := ast.NewRule(pos, name.(*ast.Identifier))
	displaySlice := toIfaceSlice(display)
	if len(displaySlice) > 0 {
		rule.DisplayName = displaySlice[0].(*ast.StringLit)
	}
	rule.Expr = expr.(ast.Expression)

	return rule, nil
}

func (v *ϡvm) callOnRule1() (interface{}, error) {
	stack := v.a.peek()
	return v.cur.onRule1(stack["name"], stack["display"], stack["expr"])
}

func (c *current) onChoiceExpr1(first, rest interface{}) (interface{}, error) {
	restSlice := toIfaceSlice(rest)
	if len(restSlice) == 0 {
		return first, nil
	}

	pos := c.astPos()
	choice := ast.NewChoiceExpr(pos)
	choice.Alternatives = []ast.Expression{first.(ast.Expression)}
	for _, sl := range restSlice {
		choice.Alternatives = append(choice.Alternatives, sl.([]interface{})[3].(ast.Expression))
	}
	return choice, nil
}

func (v *ϡvm) callOnChoiceExpr1() (interface{}, error) {
	stack := v.a.peek()
	return v.cur.onChoiceExpr1(stack["first"], stack["rest"])
}

func (c *current) onActionExpr1(expr, code interface{}) (interface{}, error) {
	if code == nil {
		return expr, nil
	}

	pos := c.astPos()
	act := ast.NewActionExpr(pos)
	act.Expr = expr.(ast.Expression)
	codeSlice := toIfaceSlice(code)
	act.Code = codeSlice[1].(*ast.CodeBlock)

	return act, nil
}

func (v *ϡvm) callOnActionExpr1() (interface{}, error) {
	stack := v.a.peek()
	return v.cur.onActionExpr1(stack["expr"], stack["code"])
}

func (c *current) onSeqExpr1(first, rest interface{}) (interface{}, error) {
	restSlice := toIfaceSlice(rest)
	if len(restSlice) == 0 {
		return first, nil
	}
	seq := ast.NewSeqExpr(c.astPos())
	seq.Exprs = []ast.Expression{first.(ast.Expression)}
	for _, sl := range restSlice {
		seq.Exprs = append(seq.Exprs, sl.([]interface{})[1].(ast.Expression))
	}
	return seq, nil
}

func (v *ϡvm) callOnSeqExpr1() (interface{}, error) {
	stack := v.a.peek()
	return v.cur.onSeqExpr1(stack["first"], stack["rest"])
}

func (c *current) onLabeledExpr2(label, expr interface{}) (interface{}, error) {
	pos := c.astPos()
	lab := ast.NewLabeledExpr(pos)
	lab.Label = label.(*ast.Identifier)
	lab.Expr = expr.(ast.Expression)
	return lab, nil
}

func (v *ϡvm) callOnLabeledExpr2() (interface{}, error) {
	stack := v.a.peek()
	return v.cur.onLabeledExpr2(stack["label"], stack["expr"])
}

func (c *current) onPrefixedExpr2(op, expr interface{}) (interface{}, error) {
	pos := c.astPos()
	opStr := op.(string)
	if opStr == "&" {
		and := ast.NewAndExpr(pos)
		and.Expr = expr.(ast.Expression)
		return and, nil
	}
	not := ast.NewNotExpr(pos)
	not.Expr = expr.(ast.Expression)
	return not, nil
}

func (v *ϡvm) callOnPrefixedExpr2() (interface{}, error) {
	stack := v.a.peek()
	return v.cur.onPrefixedExpr2(stack["op"], stack["expr"])
}

func (c *current) onPrefixedOp1() (interface{}, error) {
	return string(c.text), nil
}

func (v *ϡvm) callOnPrefixedOp1() (interface{}, error) {
	return v.cur.onPrefixedOp1()
}

func (c *current) onSuffixedExpr2(expr, op interface{}) (interface{}, error) {
	pos := c.astPos()
	opStr := op.(string)
	switch opStr {
	case "?":
		zero := ast.NewZeroOrOneExpr(pos)
		zero.Expr = expr.(ast.Expression)
		return zero, nil
	case "*":
		zero := ast.NewZeroOrMoreExpr(pos)
		zero.Expr = expr.(ast.Expression)
		return zero, nil
	case "+":
		one := ast.NewOneOrMoreExpr(pos)
		one.Expr = expr.(ast.Expression)
		return one, nil
	default:
		return nil, errors.New("unknown operator: " + opStr)
	}
}

func (v *ϡvm) callOnSuffixedExpr2() (interface{}, error) {
	stack := v.a.peek()
	return v.cur.onSuffixedExpr2(stack["expr"], stack["op"])
}

func (c *current) onSuffixedOp1() (interface{}, error) {
	return string(c.text), nil
}

func (v *ϡvm) callOnSuffixedOp1() (interface{}, error) {
	return v.cur.onSuffixedOp1()
}

func (c *current) onPrimaryExpr7(expr interface{}) (interface{}, error) {
	return expr, nil
}

func (v *ϡvm) callOnPrimaryExpr7() (interface{}, error) {
	stack := v.a.peek()
	return v.cur.onPrimaryExpr7(stack["expr"])
}

func (c *current) onRuleRefExpr1(name interface{}) (interface{}, error) {
	ref := ast.NewRuleRefExpr(c.astPos())
	ref.Name = name.(*ast.Identifier)
	return ref, nil
}

func (v *ϡvm) callOnRuleRefExpr1() (interface{}, error) {
	stack := v.a.peek()
	return v.cur.onRuleRefExpr1(stack["name"])
}

func (c *current) onSemanticPredExpr1(op, code interface{}) (interface{}, error) {
	opStr := op.(string)
	if opStr == "&" {
		and := ast.NewAndCodeExpr(c.astPos())
		and.Code = code.(*ast.CodeBlock)
		return and, nil
	}
	not := ast.NewNotCodeExpr(c.astPos())
	not.Code = code.(*ast.CodeBlock)
	return not, nil
}

func (v *ϡvm) callOnSemanticPredExpr1() (interface{}, error) {
	stack := v.a.peek()
	return v.cur.onSemanticPredExpr1(stack["op"], stack["code"])
}

func (c *current) onSemanticPredOp1() (interface{}, error) {
	return string(c.text), nil
}

func (v *ϡvm) callOnSemanticPredOp1() (interface{}, error) {
	return v.cur.onSemanticPredOp1()
}

func (c *current) onIdentifierName1() (interface{}, error) {
	return ast.NewIdentifier(c.astPos(), string(c.text)), nil
}

func (v *ϡvm) callOnIdentifierName1() (interface{}, error) {
	return v.cur.onIdentifierName1()
}

func (c *current) onLitMatcher1(lit, ignore interface{}) (interface{}, error) {
	rawStr := lit.(*ast.StringLit).Val
	s, err := strconv.Unquote(rawStr)
	if err != nil {
		return nil, err
	}
	m := ast.NewLitMatcher(c.astPos(), s)
	m.IgnoreCase = ignore != nil
	return m, nil
}

func (v *ϡvm) callOnLitMatcher1() (interface{}, error) {
	stack := v.a.peek()
	return v.cur.onLitMatcher1(stack["lit"], stack["ignore"])
}

func (c *current) onStringLiteral1() (interface{}, error) {
	return ast.NewStringLit(c.astPos(), string(c.text)), nil
}

func (v *ϡvm) callOnStringLiteral1() (interface{}, error) {
	return v.cur.onStringLiteral1()
}

func (c *current) onCharClassMatcher1() (interface{}, error) {
	pos := c.astPos()
	cc := ast.NewCharClassMatcher(pos, string(c.text))
	return cc, nil
}

func (v *ϡvm) callOnCharClassMatcher1() (interface{}, error) {
	return v.cur.onCharClassMatcher1()
}

func (c *current) onAnyMatcher1() (interface{}, error) {
	any := ast.NewAnyMatcher(c.astPos(), ".")
	return any, nil
}

func (v *ϡvm) callOnAnyMatcher1() (interface{}, error) {
	return v.cur.onAnyMatcher1()
}

func (c *current) onCodeBlock1() (interface{}, error) {
	pos := c.astPos()
	cb := ast.NewCodeBlock(pos, string(c.text))
	return cb, nil
}

func (v *ϡvm) callOnCodeBlock1() (interface{}, error) {
	return v.cur.onCodeBlock1()
}

var ϡtheProgram = &ϡprogram{
	instrs: []ϡinstr{
		{13, -1, []uint16{4, 96}}, {13, -1, []uint16{5}},
		{1, -1, nil}, {0, -1, nil},
		{13, 0, []uint16{4, 2286}}, {13, 0, []uint16{5}},
		{1, 0, nil}, {11, 0, []uint16{5}},
		{16, 0, nil}, {13, 0, []uint16{4, 131}},
		{13, 0, []uint16{5}}, {1, 0, nil},
		{11, 0, []uint16{5}}, {16, 0, nil},
		{13, 0, []uint16{4, 2286}}, {13, 0, []uint16{5}},
		{1, 0, nil}, {11, 0, []uint16{5}},
		{16, 0, nil}, {13, 0, []uint16{1}},
		{13, 0, []uint16{3, 1}}, {13, 0, []uint16{2, 9, 14}},
		{18, 0, []uint16{27}}, {1, 0, nil},
		{4, 0, nil}, {6, 0, []uint16{27}},
		{5, 0, []uint16{22}}, {11, 0, []uint16{2}},
		{15, 0, nil}, {16, 0, nil},
		{13, 0, []uint16{4, 19}}, {13, 0, []uint16{5}},
		{1, 0, nil}, {11, 0, []uint16{5}},
		{12, 0, []uint16{36}}, {16, 0, nil},
		{13, 0, []uint16{3, 0}}, {16, 0, nil},
		{13, 0, []uint16{4, 30}}, {13, 0, []uint16{5}},
		{1, 0, nil}, {11, 0, []uint16{5}},
		{17, 0, []uint16{2}}, {16, 0, nil},
		{13, 0, []uint16{4, 227}}, {13, 0, []uint16{5}},
		{1, 0, nil}, {11, 0, []uint16{5}},
		{16, 0, nil}, {13, 0, []uint16{4, 2286}},
		{13, 0, []uint16{5}}, {1, 0, nil},
		{11, 0, []uint16{5}}, {16, 0, nil},
		{13, 0, []uint16{1}}, {13, 0, []uint16{3, 1}},
		{13, 0, []uint16{2, 44, 49}}, {18, 0, []uint16{62}},
		{1, 0, nil}, {4, 0, nil},
		{6, 0, []uint16{62}}, {5, 0, []uint16{57}},
		{11, 0, []uint16{2}}, {15, 0, nil},
		{16, 0, nil}, {13, 0, []uint16{3, 1}},
		{13, 0, []uint16{4, 54}}, {13, 0, []uint16{5}},
		{1, 0, nil}, {11, 0, []uint16{5}},
		{12, 0, []uint16{73}}, {4, 0, nil},
		{5, 0, []uint16{66}}, {16, 0, nil},
		{13, 0, []uint16{4, 65}}, {13, 0, []uint16{5}},
		{1, 0, nil}, {11, 0, []uint16{5}},
		{17, 0, []uint16{4}}, {16, 0, nil},
		{13, 0, []uint16{4, 2423}}, {13, 0, []uint16{5}},
		{1, 0, nil}, {11, 0, []uint16{5}},
		{16, 0, nil}, {13, 0, []uint16{1}},
		{13, 0, []uint16{3, 1}}, {13, 0, []uint16{2, 4, 38, 74, 80}},
		{18, 0, []uint16{93}}, {1, 0, nil},
		{4, 0, nil}, {6, 0, []uint16{93}},
		{5, 0, []uint16{88}}, {11, 0, []uint16{2}},
		{15, 0, nil}, {16, 0, nil},
		{13, 0, []uint16{1}}, {13, 0, []uint16{4, 85}},
		{1, 0, nil}, {6, 0, []uint16{102}},
		{2, 0, []uint16{0}}, {16, 0, nil},
		{11, 0, []uint16{1}}, {16, 0, nil},
		{13, 3, []uint16{4, 2171}}, {13, 3, []uint16{5}},
		{1, 3, nil}, {11, 3, []uint16{5}},
		{16, 3, nil}, {13, 3, []uint16{4, 104}},
		{13, 3, []uint16{5}}, {1, 3, nil},
		{11, 3, []uint16{5}}, {17, 3, []uint16{7}},
		{16, 3, nil}, {13, 3, []uint16{4, 2408}},
		{13, 3, []uint16{5}}, {1, 3, nil},
		{11, 3, []uint16{5}}, {16, 3, nil},
		{13, 3, []uint16{1}}, {13, 3, []uint16{3, 1}},
		{13, 3, []uint16{2, 109, 115}}, {18, 3, []uint16{128}},
		{1, 3, nil}, {4, 3, nil},
		{6, 3, []uint16{128}}, {5, 3, []uint16{123}},
		{11, 3, []uint16{2}}, {15, 3, nil},
		{16, 3, nil}, {13, 3, []uint16{1}},
		{13, 3, []uint16{4, 120}}, {1, 3, nil},
		{6, 3, []uint16{137}}, {2, 3, []uint16{1}},
		{16, 3, nil}, {11, 3, []uint16{1}},
		{16, 3, nil}, {13, 5, []uint16{4, 1212}},
		{13, 5, []uint16{5}}, {1, 5, nil},
		{11, 5, []uint16{5}}, {16, 5, nil},
		{13, 5, []uint16{4, 139}}, {13, 5, []uint16{5}},
		{1, 5, nil}, {11, 5, []uint16{5}},
		{17, 5, []uint16{10}}, {16, 5, nil},
		{13, 5, []uint16{4, 2286}}, {13, 5, []uint16{5}},
		{1, 5, nil}, {11, 5, []uint16{5}},
		{16, 5, nil}, {13, 5, []uint16{4, 1384}},
		{13, 5, []uint16{5}}, {1, 5, nil},
		{11, 5, []uint16{5}}, {16, 5, nil},
		{13, 5, []uint16{4, 2286}}, {13, 5, []uint16{5}},
		{1, 5, nil}, {11, 5, []uint16{5}},
		{16, 5, nil}, {13, 5, []uint16{1}},
		{13, 5, []uint16{3, 1}}, {13, 5, []uint16{2, 155, 160}},
		{18, 5, []uint16{173}}, {1, 5, nil},
		{4, 5, nil}, {6, 5, []uint16{173}},
		{5, 5, []uint16{168}}, {11, 5, []uint16{2}},
		{15, 5, nil}, {16, 5, nil},
		{13, 5, []uint16{4, 165}}, {13, 5, []uint16{5}},
		{1, 5, nil}, {11, 5, []uint16{5}},
		{12, 5, []uint16{182}}, {16, 5, nil},
		{13, 5, []uint16{3, 0}}, {16, 5, nil},
		{13, 5, []uint16{4, 176}}, {13, 5, []uint16{5}},
		{1, 5, nil}, {11, 5, []uint16{5}},
		{17, 5, []uint16{12}}, {16, 5, nil},
		{13, 5, []uint16{4, 960}}, {13, 5, []uint16{5}},
		{1, 5, nil}, {11, 5, []uint16{5}},
		{16, 5, nil}, {13, 5, []uint16{4, 2286}},
		{13, 5, []uint16{5}}, {1, 5, nil},
		{11, 5, []uint16{5}}, {16, 5, nil},
		{13, 5, []uint16{4, 235}}, {13, 5, []uint16{5}},
		{1, 5, nil}, {11, 5, []uint16{5}},
		{16, 5, nil}, {13, 5, []uint16{4, 200}},
		{13, 5, []uint16{5}}, {1, 5, nil},
		{11, 5, []uint16{5}}, {17, 5, []uint16{15}},
		{16, 5, nil}, {13, 5, []uint16{4, 2408}},
		{13, 5, []uint16{5}}, {1, 5, nil},
		{11, 5, []uint16{5}}, {16, 5, nil},
		{13, 5, []uint16{1}}, {13, 5, []uint16{3, 1}},
		{13, 5, []uint16{2, 144, 150, 184, 190, 195, 205, 211}}, {18, 5, []uint16{224}},
		{1, 5, nil}, {4, 5, nil},
		{6, 5, []uint16{224}}, {5, 5, []uint16{219}},
		{11, 5, []uint16{2}}, {15, 5, nil},
		{16, 5, nil}, {13, 5, []uint16{1}},
		{13, 5, []uint16{4, 216}}, {1, 5, nil},
		{6, 5, []uint16{233}}, {2, 5, []uint16{2}},
		{16, 5, nil}, {11, 5, []uint16{1}},
		{16, 5, nil}, {13, 16, []uint16{4, 307}},
		{13, 16, []uint16{5}}, {1, 16, nil},
		{11, 16, []uint16{5}}, {16, 16, nil},
		{13, 17, []uint16{4, 372}}, {13, 17, []uint16{5}},
		{1, 17, nil}, {11, 17, []uint16{5}},
		{16, 17, nil}, {13, 17, []uint16{4, 240}},
		{13, 17, []uint16{5}}, {1, 17, nil},
		{11, 17, []uint16{5}}, {17, 17, []uint16{18}},
		{16, 17, nil}, {13, 17, []uint16{4, 2286}},
		{13, 17, []uint16{5}}, {1, 17, nil},
		{11, 17, []uint16{5}}, {16, 17, nil},
		{13, 17, []uint16{1}}, {8, 17, []uint16{0}},
		{15, 17, nil}, {16, 17, nil},
		{13, 17, []uint16{4, 2286}}, {13, 17, []uint16{5}},
		{1, 17, nil}, {11, 17, []uint16{5}},
		{16, 17, nil}, {13, 17, []uint16{4, 372}},
		{13, 17, []uint16{5}}, {1, 17, nil},
		{11, 17, []uint16{5}}, {16, 17, nil},
		{13, 17, []uint16{1}}, {13, 17, []uint16{3, 1}},
		{13, 17, []uint16{2, 251, 256, 260, 265}}, {18, 17, []uint16{278}},
		{1, 17, nil}, {4, 17, nil},
		{6, 17, []uint16{278}}, {5, 17, []uint16{273}},
		{11, 17, []uint16{2}}, {15, 17, nil},
		{16, 17, nil}, {13, 17, []uint16{3, 2}},
		{13, 17, []uint16{4, 270}}, {13, 17, []uint16{5}},
		{1, 17, nil}, {11, 17, []uint16{5}},
		{12, 17, []uint16{289}}, {4, 17, nil},
		{5, 17, []uint16{282}}, {16, 17, nil},
		{13, 17, []uint16{4, 281}}, {13, 17, []uint16{5}},
		{1, 17, nil}, {11, 17, []uint16{5}},
		{17, 17, []uint16{20}}, {16, 17, nil},
		{13, 17, []uint16{1}}, {13, 17, []uint16{3, 1}},
		{13, 17, []uint16{2, 245, 290}}, {18, 17, []uint16{304}},
		{1, 17, nil}, {4, 17, nil},
		{6, 17, []uint16{304}}, {5, 17, []uint16{299}},
		{11, 17, []uint16{2}}, {15, 17, nil},
		{16, 17, nil}, {13, 17, []uint16{1}},
		{13, 17, []uint16{4, 296}}, {1, 17, nil},
		{6, 17, []uint16{313}}, {2, 17, []uint16{3}},
		{16, 17, nil}, {11, 17, []uint16{1}},
		{16, 17, nil}, {13, 19, []uint16{4, 438}},
		{13, 19, []uint16{5}}, {1, 19, nil},
		{11, 19, []uint16{5}}, {16, 19, nil},
		{13, 19, []uint16{4, 315}}, {13, 19, []uint16{5}},
		{1, 19, nil}, {11, 19, []uint16{5}},
		{17, 19, []uint16{15}}, {16, 19, nil},
		{13, 19, []uint16{4, 2286}}, {13, 19, []uint16{5}},
		{1, 19, nil}, {11, 19, []uint16{5}},
		{16, 19, nil}, {13, 19, []uint16{4, 2171}},
		{13, 19, []uint16{5}}, {1, 19, nil},
		{11, 19, []uint16{5}}, {16, 19, nil},
		{13, 19, []uint16{1}}, {13, 19, []uint16{3, 1}},
		{13, 19, []uint16{2, 326, 331}}, {18, 19, []uint16{344}},
		{1, 19, nil}, {4, 19, nil},
		{6, 19, []uint16{344}}, {5, 19, []uint16{339}},
		{11, 19, []uint16{2}}, {15, 19, nil},
		{16, 19, nil}, {13, 19, []uint16{4, 336}},
		{13, 19, []uint16{5}}, {1, 19, nil},
		{11, 19, []uint16{5}}, {12, 19, []uint16{353}},
		{16, 19, nil}, {13, 19, []uint16{3, 0}},
		{16, 19, nil}, {13, 19, []uint16{4, 347}},
		{13, 19, []uint16{5}}, {1, 19, nil},
		{11, 19, []uint16{5}}, {17, 19, []uint16{7}},
		{16, 19, nil}, {13, 19, []uint16{1}},
		{13, 19, []uint16{3, 1}}, {13, 19, []uint16{2, 320, 355}},
		{18, 19, []uint16{369}}, {1, 19, nil},
		{4, 19, nil}, {6, 19, []uint16{369}},
		{5, 19, []uint16{364}}, {11, 19, []uint16{2}},
		{15, 19, nil}, {16, 19, nil},
		{13, 19, []uint16{1}}, {13, 19, []uint16{4, 361}},
		{1, 19, nil}, {6, 19, []uint16{378}},
		{2, 19, []uint16{4}}, {16, 19, nil},
		{11, 19, []uint16{1}}, {16, 19, nil},
		{13, 21, []uint16{4, 506}}, {13, 21, []uint16{5}},
		{1, 21, nil}, {11, 21, []uint16{5}},
		{16, 21, nil}, {13, 21, []uint16{4, 380}},
		{13, 21, []uint16{5}}, {1, 21, nil},
		{11, 21, []uint16{5}}, {17, 21, []uint16{18}},
		{16, 21, nil}, {13, 21, []uint16{4, 2286}},
		{13, 21, []uint16{5}}, {1, 21, nil},
		{11, 21, []uint16{5}}, {16, 21, nil},
		{13, 21, []uint16{4, 506}}, {13, 21, []uint16{5}},
		{1, 21, nil}, {11, 21, []uint16{5}},
		{16, 21, nil}, {13, 21, []uint16{1}},
		{13, 21, []uint16{3, 1}}, {13, 21, []uint16{2, 391, 396}},
		{18, 21, []uint16{409}}, {1, 21, nil},
		{4, 21, nil}, {6, 21, []uint16{409}},
		{5, 21, []uint16{404}}, {11, 21, []uint16{2}},
		{15, 21, nil}, {16, 21, nil},
		{13, 21, []uint16{3, 2}}, {13, 21, []uint16{4, 401}},
		{13, 21, []uint16{5}}, {1, 21, nil},
		{11, 21, []uint16{5}}, {12, 21, []uint16{420}},
		{4, 21, nil}, {5, 21, []uint16{413}},
		{16, 21, nil}, {13, 21, []uint16{4, 412}},
		{13, 21, []uint16{5}}, {1, 21, nil},
		{11, 21, []uint16{5}}, {17, 21, []uint16{20}},
		{16, 21, nil}, {13, 21, []uint16{1}},
		{13, 21, []uint16{3, 1}}, {13, 21, []uint16{2, 385, 421}},
		{18, 21, []uint16{435}}, {1, 21, nil},
		{4, 21, nil}, {6, 21, []uint16{435}},
		{5, 21, []uint16{430}}, {11, 21, []uint16{2}},
		{15, 21, nil}, {16, 21, nil},
		{13, 21, []uint16{1}}, {13, 21, []uint16{4, 427}},
		{1, 21, nil}, {6, 21, []uint16{444}},
		{2, 21, []uint16{5}}, {16, 21, nil},
		{11, 21, []uint16{1}}, {16, 21, nil},
		{13, 22, []uint16{4, 1177}}, {13, 22, []uint16{5}},
		{1, 22, nil}, {11, 22, []uint16{5}},
		{16, 22, nil}, {13, 22, []uint16{4, 446}},
		{13, 22, []uint16{5}}, {1, 22, nil},
		{11, 22, []uint16{5}}, {17, 22, []uint16{23}},
		{16, 22, nil}, {13, 22, []uint16{4, 2286}},
		{13, 22, []uint16{5}}, {1, 22, nil},
		{11, 22, []uint16{5}}, {16, 22, nil},
		{13, 22, []uint16{1}}, {8, 22, []uint16{1}},
		{15, 22, nil}, {16, 22, nil},
		{13, 22, []uint16{4, 2286}}, {13, 22, []uint16{5}},
		{1, 22, nil}, {11, 22, []uint16{5}},
		{16, 22, nil}, {13, 22, []uint16{4, 568}},
		{13, 22, []uint16{5}}, {1, 22, nil},
		{11, 22, []uint16{5}}, {16, 22, nil},
		{13, 22, []uint16{4, 471}}, {13, 22, []uint16{5}},
		{1, 22, nil}, {11, 22, []uint16{5}},
		{17, 22, []uint16{15}}, {16, 22, nil},
		{13, 22, []uint16{1}}, {13, 22, []uint16{3, 1}},
		{13, 22, []uint16{2, 451, 457, 462, 466, 476}}, {18, 22, []uint16{490}},
		{1, 22, nil}, {4, 22, nil},
		{6, 22, []uint16{490}}, {5, 22, []uint16{485}},
		{11, 22, []uint16{2}}, {15, 22, nil},
		{16, 22, nil}, {13, 22, []uint16{1}},
		{13, 22, []uint16{4, 482}}, {1, 22, nil},
		{6, 22, []uint16{499}}, {2, 22, []uint16{6}},
		{16, 22, nil}, {11, 22, []uint16{1}},
		{16, 22, nil}, {13, 22, []uint16{4, 568}},
		{13, 22, []uint16{5}}, {1, 22, nil},
		{11, 22, []uint16{5}}, {16, 22, nil},
		{13, 22, []uint16{2, 493, 501}}, {18, 22, []uint16{514}},
		{13, 22, []uint16{5}}, {1, 22, nil},
		{11, 22, []uint16{5}}, {7, 22, []uint16{515}},
		{11, 22, []uint16{3}}, {5, 22, []uint16{507}},
		{13, 22, []uint16{3, 1}}, {11, 22, []uint16{2}},
		{16, 22, nil}, {13, 25, []uint16{4, 598}},
		{13, 25, []uint16{5}}, {1, 25, nil},
		{11, 25, []uint16{5}}, {16, 25, nil},
		{13, 25, []uint16{4, 517}}, {13, 25, []uint16{5}},
		{1, 25, nil}, {11, 25, []uint16{5}},
		{17, 25, []uint16{26}}, {16, 25, nil},
		{13, 25, []uint16{4, 2286}}, {13, 25, []uint16{5}},
		{1, 25, nil}, {11, 25, []uint16{5}},
		{16, 25, nil}, {13, 25, []uint16{4, 657}},
		{13, 25, []uint16{5}}, {1, 25, nil},
		{11, 25, []uint16{5}}, {16, 25, nil},
		{13, 25, []uint16{4, 533}}, {13, 25, []uint16{5}},
		{1, 25, nil}, {11, 25, []uint16{5}},
		{17, 25, []uint16{15}}, {16, 25, nil},
		{13, 25, []uint16{1}}, {13, 25, []uint16{3, 1}},
		{13, 25, []uint16{2, 522, 528, 538}}, {18, 25, []uint16{552}},
		{1, 25, nil}, {4, 25, nil},
		{6, 25, []uint16{552}}, {5, 25, []uint16{547}},
		{11, 25, []uint16{2}}, {15, 25, nil},
		{16, 25, nil}, {13, 25, []uint16{1}},
		{13, 25, []uint16{4, 544}}, {1, 25, nil},
		{6, 25, []uint16{561}}, {2, 25, []uint16{7}},
		{16, 25, nil}, {11, 25, []uint16{1}},
		{16, 25, nil}, {13, 25, []uint16{4, 657}},
		{13, 25, []uint16{5}}, {1, 25, nil},
		{11, 25, []uint16{5}}, {16, 25, nil},
		{13, 25, []uint16{2, 555, 563}}, {18, 25, []uint16{576}},
		{13, 25, []uint16{5}}, {1, 25, nil},
		{11, 25, []uint16{5}}, {7, 25, []uint16{577}},
		{11, 25, []uint16{3}}, {5, 25, []uint16{569}},
		{13, 25, []uint16{3, 1}}, {11, 25, []uint16{2}},
		{16, 25, nil}, {13, 27, []uint16{1}},
		{8, 27, []uint16{2}}, {15, 27, nil},
		{16, 27, nil}, {13, 27, []uint16{1}},
		{8, 27, []uint16{3}}, {15, 27, nil},
		{16, 27, nil}, {13, 27, []uint16{2, 579, 583}},
		{18, 27, []uint16{595}}, {13, 27, []uint16{5}},
		{1, 27, nil}, {11, 27, []uint16{5}},
		{7, 27, []uint16{596}}, {11, 27, []uint16{3}},
		{5, 27, []uint16{588}}, {13, 27, []uint16{3, 1}},
		{11, 27, []uint16{2}}, {16, 27, nil},
		{13, 27, []uint16{1}}, {13, 27, []uint16{4, 587}},
		{1, 27, nil}, {6, 27, []uint16{604}},
		{2, 27, []uint16{8}}, {16, 27, nil},
		{11, 27, []uint16{1}}, {16, 27, nil},
		{13, 28, []uint16{4, 772}}, {13, 28, []uint16{5}},
		{1, 28, nil}, {11, 28, []uint16{5}},
		{16, 28, nil}, {13, 28, []uint16{4, 606}},
		{13, 28, []uint16{5}}, {1, 28, nil},
		{11, 28, []uint16{5}}, {17, 28, []uint16{15}},
		{16, 28, nil}, {13, 28, []uint16{4, 2286}},
		{13, 28, []uint16{5}}, {1, 28, nil},
		{11, 28, []uint16{5}}, {16, 28, nil},
		{13, 28, []uint16{4, 691}}, {13, 28, []uint16{5}},
		{1, 28, nil}, {11, 28, []uint16{5}},
		{16, 28, nil}, {13, 28, []uint16{4, 622}},
		{13, 28, []uint16{5}}, {1, 28, nil},
		{11, 28, []uint16{5}}, {17, 28, []uint16{26}},
		{16, 28, nil}, {13, 28, []uint16{1}},
		{13, 28, []uint16{3, 1}}, {13, 28, []uint16{2, 611, 617, 627}},
		{18, 28, []uint16{641}}, {1, 28, nil},
		{4, 28, nil}, {6, 28, []uint16{641}},
		{5, 28, []uint16{636}}, {11, 28, []uint16{2}},
		{15, 28, nil}, {16, 28, nil},
		{13, 28, []uint16{1}}, {13, 28, []uint16{4, 633}},
		{1, 28, nil}, {6, 28, []uint16{650}},
		{2, 28, []uint16{9}}, {16, 28, nil},
		{11, 28, []uint16{1}}, {16, 28, nil},
		{13, 28, []uint16{4, 772}}, {13, 28, []uint16{5}},
		{1, 28, nil}, {11, 28, []uint16{5}},
		{16, 28, nil}, {13, 28, []uint16{2, 644, 652}},
		{18, 28, []uint16{665}}, {13, 28, []uint16{5}},
		{1, 28, nil}, {11, 28, []uint16{5}},
		{7, 28, []uint16{666}}, {11, 28, []uint16{3}},
		{5, 28, []uint16{658}}, {13, 28, []uint16{3, 1}},
		{11, 28, []uint16{2}}, {16, 28, nil},
		{13, 30, []uint16{1}}, {8, 30, []uint16{4}},
		{15, 30, nil}, {16, 30, nil},
		{13, 30, []uint16{1}}, {8, 30, []uint16{5}},
		{15, 30, nil}, {16, 30, nil},
		{13, 30, []uint16{1}}, {8, 30, []uint16{6}},
		{15, 30, nil}, {16, 30, nil},
		{13, 30, []uint16{2, 668, 672, 676}}, {18, 30, []uint16{688}},
		{13, 30, []uint16{5}}, {1, 30, nil},
		{11, 30, []uint16{5}}, {7, 30, []uint16{689}},
		{11, 30, []uint16{3}}, {5, 30, []uint16{681}},
		{13, 30, []uint16{3, 1}}, {11, 30, []uint16{2}},
		{16, 30, nil}, {13, 30, []uint16{1}},
		{13, 30, []uint16{4, 680}}, {1, 30, nil},
		{6, 30, []uint16{697}}, {2, 30, []uint16{10}},
		{16, 30, nil}, {11, 30, []uint16{1}},
		{16, 30, nil}, {13, 29, []uint16{4, 1284}},
		{13, 29, []uint16{5}}, {1, 29, nil},
		{11, 29, []uint16{5}}, {16, 29, nil},
		{13, 29, []uint16{4, 1927}}, {13, 29, []uint16{5}},
		{1, 29, nil}, {11, 29, []uint16{5}},
		{16, 29, nil}, {13, 29, []uint16{4, 2139}},
		{13, 29, []uint16{5}}, {1, 29, nil},
		{11, 29, []uint16{5}}, {16, 29, nil},
		{13, 29, []uint16{4, 863}}, {13, 29, []uint16{5}},
		{1, 29, nil}, {11, 29, []uint16{5}},
		{16, 29, nil}, {13, 29, []uint16{4, 909}},
		{13, 29, []uint16{5}}, {1, 29, nil},
		{11, 29, []uint16{5}}, {16, 29, nil},
		{13, 29, []uint16{1}}, {8, 29, []uint16{7}},
		{15, 29, nil}, {16, 29, nil},
		{13, 29, []uint16{4, 2286}}, {13, 29, []uint16{5}},
		{1, 29, nil}, {11, 29, []uint16{5}},
		{16, 29, nil}, {13, 29, []uint16{4, 235}},
		{13, 29, []uint16{5}}, {1, 29, nil},
		{11, 29, []uint16{5}}, {16, 29, nil},
		{13, 29, []uint16{4, 733}}, {13, 29, []uint16{5}},
		{1, 29, nil}, {11, 29, []uint16{5}},
		{17, 29, []uint16{15}}, {16, 29, nil},
		{13, 29, []uint16{4, 2286}}, {13, 29, []uint16{5}},
		{1, 29, nil}, {11, 29, []uint16{5}},
		{16, 29, nil}, {13, 29, []uint16{1}},
		{8, 29, []uint16{8}}, {15, 29, nil},
		{16, 29, nil}, {13, 29, []uint16{1}},
		{13, 29, []uint16{3, 1}}, {13, 29, []uint16{2, 724, 728, 738, 744, 749}},
		{18, 29, []uint16{761}}, {1, 29, nil},
		{4, 29, nil}, {6, 29, []uint16{761}},
		{5, 29, []uint16{756}}, {11, 29, []uint16{2}},
		{15, 29, nil}, {16, 29, nil},
		{13, 29, []uint16{1}}, {13, 29, []uint16{4, 753}},
		{1, 29, nil}, {6, 29, []uint16{770}},
		{2, 29, []uint16{11}}, {16, 29, nil},
		{11, 29, []uint16{1}}, {16, 29, nil},
		{13, 29, []uint16{2, 699, 704, 709, 714, 719, 764}}, {18, 29, []uint16{780}},
		{13, 29, []uint16{5}}, {1, 29, nil},
		{11, 29, []uint16{5}}, {7, 29, []uint16{781}},
		{11, 29, []uint16{3}}, {5, 29, []uint16{773}},
		{13, 29, []uint16{3, 1}}, {11, 29, []uint16{2}},
		{16, 29, nil}, {13, 34, []uint16{4, 1212}},
		{13, 34, []uint16{5}}, {1, 34, nil},
		{11, 34, []uint16{5}}, {16, 34, nil},
		{13, 34, []uint16{4, 783}}, {13, 34, []uint16{5}},
		{1, 34, nil}, {11, 34, []uint16{5}},
		{17, 34, []uint16{10}}, {16, 34, nil},
		{13, 34, []uint16{4, 2286}}, {13, 34, []uint16{5}},
		{1, 34, nil}, {11, 34, []uint16{5}},
		{16, 34, nil}, {13, 34, []uint16{4, 1384}},
		{13, 34, []uint16{5}}, {1, 34, nil},
		{11, 34, []uint16{5}}, {16, 34, nil},
		{13, 34, []uint16{4, 2286}}, {13, 34, []uint16{5}},
		{1, 34, nil}, {11, 34, []uint16{5}},
		{16, 34, nil}, {13, 34, []uint16{1}},
		{13, 34, []uint16{3, 1}}, {13, 34, []uint16{2, 799, 804}},
		{18, 34, []uint16{817}}, {1, 34, nil},
		{4, 34, nil}, {6, 34, []uint16{817}},
		{5, 34, []uint16{812}}, {11, 34, []uint16{2}},
		{15, 34, nil}, {16, 34, nil},
		{13, 34, []uint16{4, 809}}, {13, 34, []uint16{5}},
		{1, 34, nil}, {11, 34, []uint16{5}},
		{12, 34, []uint16{826}}, {16, 34, nil},
		{13, 34, []uint16{3, 0}}, {16, 34, nil},
		{13, 34, []uint16{4, 960}}, {13, 34, []uint16{5}},
		{1, 34, nil}, {11, 34, []uint16{5}},
		{16, 34, nil}, {13, 34, []uint16{1}},
		{13, 34, []uint16{3, 1}}, {13, 34, []uint16{2, 794, 820, 828}},
		{18, 34, []uint16{841}}, {1, 34, nil},
		{4, 34, nil}, {6, 34, []uint16{841}},
		{5, 34, []uint16{836}}, {11, 34, []uint16{2}},
		{15, 34, nil}, {16, 34, nil},
		{13, 34, []uint16{1}}, {13, 34, []uint16{4, 833}},
		{13, 34, []uint16{5}}, {1, 34, nil},
		{11, 34, []uint16{5}}, {9, 34, nil},
		{14, 34, nil}, {16, 34, nil},
		{13, 34, []uint16{1}}, {13, 34, []uint16{3, 1}},
		{13, 34, []uint16{2, 788, 844}}, {18, 34, []uint16{860}},
		{1, 34, nil}, {4, 34, nil},
		{6, 34, []uint16{860}}, {5, 34, []uint16{855}},
		{11, 34, []uint16{2}}, {15, 34, nil},
		{16, 34, nil}, {13, 34, []uint16{1}},
		{13, 34, []uint16{4, 852}}, {1, 34, nil},
		{6, 34, []uint16{869}}, {2, 34, []uint16{12}},
		{16, 34, nil}, {11, 34, []uint16{1}},
		{16, 34, nil}, {13, 35, []uint16{4, 936}},
		{13, 35, []uint16{5}}, {1, 35, nil},
		{11, 35, []uint16{5}}, {16, 35, nil},
		{13, 35, []uint16{4, 871}}, {13, 35, []uint16{5}},
		{1, 35, nil}, {11, 35, []uint16{5}},
		{17, 35, []uint16{26}}, {16, 35, nil},
		{13, 35, []uint16{4, 2286}}, {13, 35, []uint16{5}},
		{1, 35, nil}, {11, 35, []uint16{5}},
		{16, 35, nil}, {13, 35, []uint16{4, 2171}},
		{13, 35, []uint16{5}}, {1, 35, nil},
		{11, 35, []uint16{5}}, {16, 35, nil},
		{13, 35, []uint16{4, 887}}, {13, 35, []uint16{5}},
		{1, 35, nil}, {11, 35, []uint16{5}},
		{17, 35, []uint16{7}}, {16, 35, nil},
		{13, 35, []uint16{1}}, {13, 35, []uint16{3, 1}},
		{13, 35, []uint16{2, 876, 882, 892}}, {18, 35, []uint16{906}},
		{1, 35, nil}, {4, 35, nil},
		{6, 35, []uint16{906}}, {5, 35, []uint16{901}},
		{11, 35, []uint16{2}}, {15, 35, nil},
		{16, 35, nil}, {13, 35, []uint16{1}},
		{13, 35, []uint16{4, 898}}, {1, 35, nil},
		{6, 35, []uint16{915}}, {2, 35, []uint16{13}},
		{16, 35, nil}, {11, 35, []uint16{1}},
		{16, 35, nil}, {13, 36, []uint16{1}},
		{8, 36, []uint16{2}}, {15, 36, nil},
		{16, 36, nil}, {13, 36, []uint16{1}},
		{8, 36, []uint16{3}}, {15, 36, nil},
		{16, 36, nil}, {13, 36, []uint16{2, 917, 921}},
		{18, 36, []uint16{933}}, {13, 36, []uint16{5}},
		{1, 36, nil}, {11, 36, []uint16{5}},
		{7, 36, []uint16{934}}, {11, 36, []uint16{3}},
		{5, 36, []uint16{926}}, {13, 36, []uint16{3, 1}},
		{11, 36, []uint16{2}}, {16, 36, nil},
		{13, 36, []uint16{1}}, {13, 36, []uint16{4, 925}},
		{1, 36, nil}, {6, 36, []uint16{942}},
		{2, 36, []uint16{14}}, {16, 36, nil},
		{11, 36, []uint16{1}}, {16, 36, nil},
		{13, 14, []uint16{1}}, {8, 14, []uint16{9}},
		{15, 14, nil}, {16, 14, nil},
		{13, 14, []uint16{1}}, {8, 14, []uint16{10}},
		{15, 14, nil}, {16, 14, nil},
		{13, 14, []uint16{1}}, {8, 14, []uint16{11}},
		{15, 14, nil}, {16, 14, nil},
		{13, 14, []uint16{1}}, {8, 14, []uint16{12}},
		{15, 14, nil}, {16, 14, nil},
		{13, 14, []uint16{2, 944, 948, 952, 956}}, {18, 14, []uint16{968}},
		{13, 14, []uint16{5}}, {1, 14, nil},
		{11, 14, []uint16{5}}, {7, 14, []uint16{969}},
		{11, 14, []uint16{3}}, {5, 14, []uint16{961}},
		{13, 14, []uint16{3, 1}}, {11, 14, []uint16{2}},
		{16, 14, nil}, {13, 37, []uint16{1}},
		{8, 37, []uint16{13}}, {15, 37, nil},
		{16, 37, nil}, {13, 38, []uint16{4, 1041}},
		{13, 38, []uint16{5}}, {1, 38, nil},
		{11, 38, []uint16{5}}, {16, 38, nil},
		{13, 38, []uint16{4, 1166}}, {13, 38, []uint16{5}},
		{1, 38, nil}, {11, 38, []uint16{5}},
		{16, 38, nil}, {13, 38, []uint16{2, 975, 980}},
		{18, 38, []uint16{993}}, {13, 38, []uint16{5}},
		{1, 38, nil}, {11, 38, []uint16{5}},
		{7, 38, []uint16{994}}, {11, 38, []uint16{3}},
		{5, 38, []uint16{986}}, {13, 38, []uint16{3, 1}},
		{11, 38, []uint16{2}}, {16, 38, nil},
		{13, 39, []uint16{1}}, {8, 39, []uint16{14}},
		{15, 39, nil}, {16, 39, nil},
		{13, 39, []uint16{1}}, {8, 39, []uint16{15}},
		{15, 39, nil}, {16, 39, nil},
		{13, 39, []uint16{1}}, {13, 39, []uint16{4, 1000}},
		{13, 39, []uint16{5}}, {1, 39, nil},
		{11, 39, []uint16{5}}, {9, 39, nil},
		{14, 39, nil}, {16, 39, nil},
		{13, 39, []uint16{4, 971}}, {13, 39, []uint16{5}},
		{1, 39, nil}, {11, 39, []uint16{5}},
		{16, 39, nil}, {13, 39, []uint16{1}},
		{13, 39, []uint16{3, 1}}, {13, 39, []uint16{2, 1004, 1012}},
		{18, 39, []uint16{1025}}, {1, 39, nil},
		{4, 39, nil}, {6, 39, []uint16{1025}},
		{5, 39, []uint16{1020}}, {11, 39, []uint16{2}},
		{15, 39, nil}, {16, 39, nil},
		{13, 39, []uint16{3, 2}}, {13, 39, []uint16{4, 1017}},
		{13, 39, []uint16{5}}, {1, 39, nil},
		{11, 39, []uint16{5}}, {12, 39, []uint16{1036}},
		{4, 39, nil}, {5, 39, []uint16{1029}},
		{16, 39, nil}, {13, 39, []uint16{1}},
		{8, 39, []uint16{15}}, {15, 39, nil},
		{16, 39, nil}, {13, 39, []uint16{1}},
		{13, 39, []uint16{3, 1}}, {13, 39, []uint16{2, 996, 1028, 1037}},
		{18, 39, []uint16{1049}}, {1, 39, nil},
		{4, 39, nil}, {6, 39, []uint16{1049}},
		{5, 39, []uint16{1044}}, {11, 39, []uint16{2}},
		{15, 39, nil}, {16, 39, nil},
		{13, 41, []uint16{1}}, {8, 41, []uint16{14}},
		{15, 41, nil}, {16, 41, nil},
		{13, 41, []uint16{1}}, {8, 41, []uint16{15}},
		{15, 41, nil}, {16, 41, nil},
		{13, 41, []uint16{4, 2329}}, {13, 41, []uint16{5}},
		{1, 41, nil}, {11, 41, []uint16{5}},
		{16, 41, nil}, {13, 41, []uint16{2, 1056, 1060}},
		{18, 41, []uint16{1073}}, {13, 41, []uint16{5}},
		{1, 41, nil}, {11, 41, []uint16{5}},
		{7, 41, []uint16{1074}}, {11, 41, []uint16{3}},
		{5, 41, []uint16{1066}}, {13, 41, []uint16{3, 1}},
		{11, 41, []uint16{2}}, {16, 41, nil},
		{13, 41, []uint16{1}}, {13, 41, []uint16{4, 1065}},
		{13, 41, []uint16{5}}, {1, 41, nil},
		{11, 41, []uint16{5}}, {9, 41, nil},
		{14, 41, nil}, {16, 41, nil},
		{13, 41, []uint16{4, 971}}, {13, 41, []uint16{5}},
		{1, 41, nil}, {11, 41, []uint16{5}},
		{16, 41, nil}, {13, 41, []uint16{1}},
		{13, 41, []uint16{3, 1}}, {13, 41, []uint16{2, 1076, 1084}},
		{18, 41, []uint16{1097}}, {1, 41, nil},
		{4, 41, nil}, {6, 41, []uint16{1097}},
		{5, 41, []uint16{1092}}, {11, 41, []uint16{2}},
		{15, 41, nil}, {16, 41, nil},
		{13, 41, []uint16{3, 2}}, {13, 41, []uint16{4, 1089}},
		{13, 41, []uint16{5}}, {1, 41, nil},
		{11, 41, []uint16{5}}, {12, 41, []uint16{1108}},
		{4, 41, nil}, {5, 41, []uint16{1101}},
		{16, 41, nil}, {13, 41, []uint16{1}},
		{8, 41, []uint16{15}}, {15, 41, nil},
		{16, 41, nil}, {13, 41, []uint16{1}},
		{13, 41, []uint16{3, 1}}, {13, 41, []uint16{2, 1052, 1100, 1109}},
		{18, 41, []uint16{1121}}, {1, 41, nil},
		{4, 41, nil}, {6, 41, []uint16{1121}},
		{5, 41, []uint16{1116}}, {11, 41, []uint16{2}},
		{15, 41, nil}, {16, 41, nil},
		{13, 40, []uint16{1}}, {8, 40, []uint16{16}},
		{15, 40, nil}, {16, 40, nil},
		{13, 40, []uint16{4, 2329}}, {13, 40, []uint16{5}},
		{1, 40, nil}, {11, 40, []uint16{5}},
		{16, 40, nil}, {13, 40, []uint16{1}},
		{13, 40, []uint16{4, 1128}}, {13, 40, []uint16{5}},
		{1, 40, nil}, {11, 40, []uint16{5}},
		{9, 40, nil}, {14, 40, nil},
		{16, 40, nil}, {13, 40, []uint16{4, 971}},
		{13, 40, []uint16{5}}, {1, 40, nil},
		{11, 40, []uint16{5}}, {16, 40, nil},
		{13, 40, []uint16{1}}, {13, 40, []uint16{3, 1}},
		{13, 40, []uint16{2, 1133, 1141}}, {18, 40, []uint16{1154}},
		{1, 40, nil}, {4, 40, nil},
		{6, 40, []uint16{1154}}, {5, 40, []uint16{1149}},
		{11, 40, []uint16{2}}, {15, 40, nil},
		{16, 40, nil}, {13, 40, []uint16{3, 2}},
		{13, 40, []uint16{4, 1146}}, {13, 40, []uint16{5}},
		{1, 40, nil}, {11, 40, []uint16{5}},
		{12, 40, []uint16{1165}}, {4, 40, nil},
		{5, 40, []uint16{1158}}, {16, 40, nil},
		{13, 40, []uint16{1}}, {13, 40, []uint16{3, 1}},
		{13, 40, []uint16{2, 1124, 1157}}, {18, 40, []uint16{1174}},
		{1, 40, nil}, {4, 40, nil},
		{6, 40, []uint16{1174}}, {5, 40, []uint16{1169}},
		{11, 40, []uint16{2}}, {15, 40, nil},
		{16, 40, nil}, {13, 24, []uint16{4, 1212}},
		{13, 24, []uint16{5}}, {1, 24, nil},
		{11, 24, []uint16{5}}, {16, 24, nil},
		{13, 11, []uint16{4, 1220}}, {13, 11, []uint16{5}},
		{1, 11, nil}, {11, 11, []uint16{5}},
		{16, 11, nil}, {13, 11, []uint16{4, 1233}},
		{13, 11, []uint16{5}}, {1, 11, nil},
		{11, 11, []uint16{5}}, {16, 11, nil},
		{13, 11, []uint16{3, 2}}, {13, 11, []uint16{4, 1187}},
		{13, 11, []uint16{5}}, {1, 11, nil},
		{11, 11, []uint16{5}}, {12, 11, []uint16{1200}},
		{4, 11, nil}, {5, 11, []uint16{1193}},
		{16, 11, nil}, {13, 11, []uint16{1}},
		{13, 11, []uint16{3, 1}}, {13, 11, []uint16{2, 1182, 1192}},
		{18, 11, []uint16{1209}}, {1, 11, nil},
		{4, 11, nil}, {6, 11, []uint16{1209}},
		{5, 11, []uint16{1204}}, {11, 11, []uint16{2}},
		{15, 11, nil}, {16, 11, nil},
		{13, 11, []uint16{1}}, {13, 11, []uint16{4, 1201}},
		{1, 11, nil}, {6, 11, []uint16{1218}},
		{2, 11, []uint16{15}}, {16, 11, nil},
		{11, 11, []uint16{1}}, {16, 11, nil},
		{13, 43, []uint16{1}}, {8, 43, []uint16{17}},
		{15, 43, nil}, {16, 43, nil},
		{13, 44, []uint16{4, 1220}}, {13, 44, []uint16{5}},
		{1, 44, nil}, {11, 44, []uint16{5}},
		{16, 44, nil}, {13, 44, []uint16{1}},
		{8, 44, []uint16{18}}, {15, 44, nil},
		{16, 44, nil}, {13, 44, []uint16{2, 1224, 1229}},
		{18, 44, []uint16{1241}}, {13, 44, []uint16{5}},
		{1, 44, nil}, {11, 44, []uint16{5}},
		{7, 44, []uint16{1242}}, {11, 44, []uint16{3}},
		{5, 44, []uint16{1234}}, {13, 44, []uint16{3, 1}},
		{11, 44, []uint16{2}}, {16, 44, nil},
		{13, 31, []uint16{4, 1384}}, {13, 31, []uint16{5}},
		{1, 31, nil}, {11, 31, []uint16{5}},
		{16, 31, nil}, {13, 31, []uint16{4, 1244}},
		{13, 31, []uint16{5}}, {1, 31, nil},
		{11, 31, []uint16{5}}, {17, 31, []uint16{45}},
		{16, 31, nil}, {13, 31, []uint16{1}},
		{8, 31, []uint16{19}}, {15, 31, nil},
		{16, 31, nil}, {13, 31, []uint16{4, 1255}},
		{13, 31, []uint16{5}}, {1, 31, nil},
		{11, 31, []uint16{5}}, {12, 31, []uint16{1265}},
		{16, 31, nil}, {13, 31, []uint16{3, 0}},
		{16, 31, nil}, {13, 31, []uint16{4, 1259}},
		{13, 31, []uint16{5}}, {1, 31, nil},
		{11, 31, []uint16{5}}, {17, 31, []uint16{46}},
		{16, 31, nil}, {13, 31, []uint16{1}},
		{13, 31, []uint16{3, 1}}, {13, 31, []uint16{2, 1249, 1267}},
		{18, 31, []uint16{1281}}, {1, 31, nil},
		{4, 31, nil}, {6, 31, []uint16{1281}},
		{5, 31, []uint16{1276}}, {11, 31, []uint16{2}},
		{15, 31, nil}, {16, 31, nil},
		{13, 31, []uint16{1}}, {13, 31, []uint16{4, 1273}},
		{1, 31, nil}, {6, 31, []uint16{1290}},
		{2, 31, []uint16{16}}, {16, 31, nil},
		{11, 31, []uint16{1}}, {16, 31, nil},
		{13, 13, []uint16{1}}, {8, 13, []uint16{20}},
		{15, 13, nil}, {16, 13, nil},
		{13, 13, []uint16{4, 1460}}, {13, 13, []uint16{5}},
		{1, 13, nil}, {11, 13, []uint16{5}},
		{16, 13, nil}, {13, 13, []uint16{3, 2}},
		{13, 13, []uint16{4, 1296}}, {13, 13, []uint16{5}},
		{1, 13, nil}, {11, 13, []uint16{5}},
		{12, 13, []uint16{1309}}, {4, 13, nil},
		{5, 13, []uint16{1302}}, {16, 13, nil},
		{13, 13, []uint16{1}}, {8, 13, []uint16{20}},
		{15, 13, nil}, {16, 13, nil},
		{13, 13, []uint16{1}}, {13, 13, []uint16{3, 1}},
		{13, 13, []uint16{2, 1292, 1301, 1310}}, {18, 13, []uint16{1322}},
		{1, 13, nil}, {4, 13, nil},
		{6, 13, []uint16{1322}}, {5, 13, []uint16{1317}},
		{11, 13, []uint16{2}}, {15, 13, nil},
		{16, 13, nil}, {13, 13, []uint16{1}},
		{8, 13, []uint16{21}}, {15, 13, nil},
		{16, 13, nil}, {13, 13, []uint16{4, 1539}},
		{13, 13, []uint16{5}}, {1, 13, nil},
		{11, 13, []uint16{5}}, {16, 13, nil},
		{13, 13, []uint16{1}}, {8, 13, []uint16{21}},
		{15, 13, nil}, {16, 13, nil},
		{13, 13, []uint16{1}}, {13, 13, []uint16{3, 1}},
		{13, 13, []uint16{2, 1325, 1329, 1334}}, {18, 13, []uint16{1346}},
		{1, 13, nil}, {4, 13, nil},
		{6, 13, []uint16{1346}}, {5, 13, []uint16{1341}},
		{11, 13, []uint16{2}}, {15, 13, nil},
		{16, 13, nil}, {13, 13, []uint16{1}},
		{8, 13, []uint16{22}}, {15, 13, nil},
		{16, 13, nil}, {13, 13, []uint16{4, 1567}},
		{13, 13, []uint16{5}}, {1, 13, nil},
		{11, 13, []uint16{5}}, {16, 13, nil},
		{13, 13, []uint16{1}}, {8, 13, []uint16{22}},
		{15, 13, nil}, {16, 13, nil},
		{13, 13, []uint16{1}}, {13, 13, []uint16{3, 1}},
		{13, 13, []uint16{2, 1349, 1353, 1358}}, {18, 13, []uint16{1370}},
		{1, 13, nil}, {4, 13, nil},
		{6, 13, []uint16{1370}}, {5, 13, []uint16{1365}},
		{11, 13, []uint16{2}}, {15, 13, nil},
		{16, 13, nil}, {13, 13, []uint16{2, 1314, 1338, 1362}},
		{18, 13, []uint16{1381}}, {13, 13, []uint16{5}},
		{1, 13, nil}, {11, 13, []uint16{5}},
		{7, 13, []uint16{1382}}, {11, 13, []uint16{3}},
		{5, 13, []uint16{1374}}, {13, 13, []uint16{3, 1}},
		{11, 13, []uint16{2}}, {16, 13, nil},
		{13, 13, []uint16{1}}, {13, 13, []uint16{4, 1373}},
		{1, 13, nil}, {6, 13, []uint16{1390}},
		{2, 13, []uint16{17}}, {16, 13, nil},
		{11, 13, []uint16{1}}, {16, 13, nil},
		{13, 47, []uint16{1}}, {8, 47, []uint16{20}},
		{15, 47, nil}, {16, 47, nil},
		{13, 47, []uint16{1}}, {8, 47, []uint16{23}},
		{15, 47, nil}, {16, 47, nil},
		{13, 47, []uint16{4, 2329}}, {13, 47, []uint16{5}},
		{1, 47, nil}, {11, 47, []uint16{5}},
		{16, 47, nil}, {13, 47, []uint16{2, 1392, 1396, 1400}},
		{18, 47, []uint16{1413}}, {13, 47, []uint16{5}},
		{1, 47, nil}, {11, 47, []uint16{5}},
		{7, 47, []uint16{1414}}, {11, 47, []uint16{3}},
		{5, 47, []uint16{1406}}, {13, 47, []uint16{3, 1}},
		{11, 47, []uint16{2}}, {16, 47, nil},
		{13, 47, []uint16{1}}, {13, 47, []uint16{4, 1405}},
		{13, 47, []uint16{5}}, {1, 47, nil},
		{11, 47, []uint16{5}}, {9, 47, nil},
		{14, 47, nil}, {16, 47, nil},
		{13, 47, []uint16{4, 971}}, {13, 47, []uint16{5}},
		{1, 47, nil}, {11, 47, []uint16{5}},
		{16, 47, nil}, {13, 47, []uint16{1}},
		{13, 47, []uint16{3, 1}}, {13, 47, []uint16{2, 1416, 1424}},
		{18, 47, []uint16{1437}}, {1, 47, nil},
		{4, 47, nil}, {6, 47, []uint16{1437}},
		{5, 47, []uint16{1432}}, {11, 47, []uint16{2}},
		{15, 47, nil}, {16, 47, nil},
		{13, 47, []uint16{1}}, {8, 47, []uint16{23}},
		{15, 47, nil}, {16, 47, nil},
		{13, 47, []uint16{4, 1587}}, {13, 47, []uint16{5}},
		{1, 47, nil}, {11, 47, []uint16{5}},
		{16, 47, nil}, {13, 47, []uint16{1}},
		{13, 47, []uint16{3, 1}}, {13, 47, []uint16{2, 1440, 1444}},
		{18, 47, []uint16{1457}}, {1, 47, nil},
		{4, 47, nil}, {6, 47, []uint16{1457}},
		{5, 47, []uint16{1452}}, {11, 47, []uint16{2}},
		{15, 47, nil}, {16, 47, nil},
		{13, 47, []uint16{2, 1429, 1449}}, {18, 47, []uint16{1468}},
		{13, 47, []uint16{5}}, {1, 47, nil},
		{11, 47, []uint16{5}}, {7, 47, []uint16{1469}},
		{11, 47, []uint16{3}}, {5, 47, []uint16{1461}},
		{13, 47, []uint16{3, 1}}, {11, 47, []uint16{2}},
		{16, 47, nil}, {13, 48, []uint16{1}},
		{8, 48, []uint16{21}}, {15, 48, nil},
		{16, 48, nil}, {13, 48, []uint16{1}},
		{8, 48, []uint16{23}}, {15, 48, nil},
		{16, 48, nil}, {13, 48, []uint16{4, 2329}},
		{13, 48, []uint16{5}}, {1, 48, nil},
		{11, 48, []uint16{5}}, {16, 48, nil},
		{13, 48, []uint16{2, 1471, 1475, 1479}}, {18, 48, []uint16{1492}},
		{13, 48, []uint16{5}}, {1, 48, nil},
		{11, 48, []uint16{5}}, {7, 48, []uint16{1493}},
		{11, 48, []uint16{3}}, {5, 48, []uint16{1485}},
		{13, 48, []uint16{3, 1}}, {11, 48, []uint16{2}},
		{16, 48, nil}, {13, 48, []uint16{1}},
		{13, 48, []uint16{4, 1484}}, {13, 48, []uint16{5}},
		{1, 48, nil}, {11, 48, []uint16{5}},
		{9, 48, nil}, {14, 48, nil},
		{16, 48, nil}, {13, 48, []uint16{4, 971}},
		{13, 48, []uint16{5}}, {1, 48, nil},
		{11, 48, []uint16{5}}, {16, 48, nil},
		{13, 48, []uint16{1}}, {13, 48, []uint16{3, 1}},
		{13, 48, []uint16{2, 1495, 1503}}, {18, 48, []uint16{1516}},
		{1, 48, nil}, {4, 48, nil},
		{6, 48, []uint16{1516}}, {5, 48, []uint16{1511}},
		{11, 48, []uint16{2}}, {15, 48, nil},
		{16, 48, nil}, {13, 48, []uint16{1}},
		{8, 48, []uint16{23}}, {15, 48, nil},
		{16, 48, nil}, {13, 48, []uint16{4, 1607}},
		{13, 48, []uint16{5}}, {1, 48, nil},
		{11, 48, []uint16{5}}, {16, 48, nil},
		{13, 48, []uint16{1}}, {13, 48, []uint16{3, 1}},
		{13, 48, []uint16{2, 1519, 1523}}, {18, 48, []uint16{1536}},
		{1, 48, nil}, {4, 48, nil},
		{6, 48, []uint16{1536}}, {5, 48, []uint16{1531}},
		{11, 48, []uint16{2}}, {15, 48, nil},
		{16, 48, nil}, {13, 48, []uint16{2, 1508, 1528}},
		{18, 48, []uint16{1547}}, {13, 48, []uint16{5}},
		{1, 48, nil}, {11, 48, []uint16{5}},
		{7, 48, []uint16{1548}}, {11, 48, []uint16{3}},
		{5, 48, []uint16{1540}}, {13, 48, []uint16{3, 1}},
		{11, 48, []uint16{2}}, {16, 48, nil},
		{13, 49, []uint16{1}}, {8, 49, []uint16{22}},
		{15, 49, nil}, {16, 49, nil},
		{13, 49, []uint16{1}}, {13, 49, []uint16{4, 1550}},
		{13, 49, []uint16{5}}, {1, 49, nil},
		{11, 49, []uint16{5}}, {9, 49, nil},
		{14, 49, nil}, {16, 49, nil},
		{13, 49, []uint16{4, 971}}, {13, 49, []uint16{5}},
		{1, 49, nil}, {11, 49, []uint16{5}},
		{16, 49, nil}, {13, 49, []uint16{1}},
		{13, 49, []uint16{3, 1}}, {13, 49, []uint16{2, 1554, 1562}},
		{18, 49, []uint16{1575}}, {1, 49, nil},
		{4, 49, nil}, {6, 49, []uint16{1575}},
		{5, 49, []uint16{1570}}, {11, 49, []uint16{2}},
		{15, 49, nil}, {16, 49, nil},
		{13, 50, []uint16{1}}, {8, 50, []uint16{21}},
		{15, 50, nil}, {16, 50, nil},
		{13, 50, []uint16{4, 1643}}, {13, 50, []uint16{5}},
		{1, 50, nil}, {11, 50, []uint16{5}},
		{16, 50, nil}, {13, 50, []uint16{2, 1578, 1582}},
		{18, 50, []uint16{1595}}, {13, 50, []uint16{5}},
		{1, 50, nil}, {11, 50, []uint16{5}},
		{7, 50, []uint16{1596}}, {11, 50, []uint16{3}},
		{5, 50, []uint16{1588}}, {13, 50, []uint16{3, 1}},
		{11, 50, []uint16{2}}, {16, 50, nil},
		{13, 51, []uint16{1}}, {8, 51, []uint16{20}},
		{15, 51, nil}, {16, 51, nil},
		{13, 51, []uint16{4, 1643}}, {13, 51, []uint16{5}},
		{1, 51, nil}, {11, 51, []uint16{5}},
		{16, 51, nil}, {13, 51, []uint16{2, 1598, 1602}},
		{18, 51, []uint16{1615}}, {13, 51, []uint16{5}},
		{1, 51, nil}, {11, 51, []uint16{5}},
		{7, 51, []uint16{1616}}, {11, 51, []uint16{3}},
		{5, 51, []uint16{1608}}, {13, 51, []uint16{3, 1}},
		{11, 51, []uint16{2}}, {16, 51, nil},
		{13, 52, []uint16{4, 1686}}, {13, 52, []uint16{5}},
		{1, 52, nil}, {11, 52, []uint16{5}},
		{16, 52, nil}, {13, 52, []uint16{4, 1712}},
		{13, 52, []uint16{5}}, {1, 52, nil},
		{11, 52, []uint16{5}}, {16, 52, nil},
		{13, 52, []uint16{4, 1737}}, {13, 52, []uint16{5}},
		{1, 52, nil}, {11, 52, []uint16{5}},
		{16, 52, nil}, {13, 52, []uint16{4, 1792}},
		{13, 52, []uint16{5}}, {1, 52, nil},
		{11, 52, []uint16{5}}, {16, 52, nil},
		{13, 52, []uint16{4, 1827}}, {13, 52, []uint16{5}},
		{1, 52, nil}, {11, 52, []uint16{5}},
		{16, 52, nil}, {13, 52, []uint16{2, 1618, 1623, 1628, 1633, 1638}},
		{18, 52, []uint16{1651}}, {13, 52, []uint16{5}},
		{1, 52, nil}, {11, 52, []uint16{5}},
		{7, 52, []uint16{1652}}, {11, 52, []uint16{3}},
		{5, 52, []uint16{1644}}, {13, 52, []uint16{3, 1}},
		{11, 52, []uint16{2}}, {16, 52, nil},
		{13, 53, []uint16{1}}, {8, 53, []uint16{24}},
		{15, 53, nil}, {16, 53, nil},
		{13, 53, []uint16{1}}, {8, 53, []uint16{25}},
		{15, 53, nil}, {16, 53, nil},
		{13, 53, []uint16{1}}, {8, 53, []uint16{26}},
		{15, 53, nil}, {16, 53, nil},
		{13, 53, []uint16{1}}, {8, 53, []uint16{27}},
		{15, 53, nil}, {16, 53, nil},
		{13, 53, []uint16{1}}, {8, 53, []uint16{28}},
		{15, 53, nil}, {16, 53, nil},
		{13, 53, []uint16{1}}, {8, 53, []uint16{29}},
		{15, 53, nil}, {16, 53, nil},
		{13, 53, []uint16{1}}, {8, 53, []uint16{30}},
		{15, 53, nil}, {16, 53, nil},
		{13, 53, []uint16{1}}, {8, 53, []uint16{23}},
		{15, 53, nil}, {16, 53, nil},
		{13, 53, []uint16{2, 1654, 1658, 1662, 1666, 1670, 1674, 1678, 1682}}, {18, 53, []uint16{1694}},
		{13, 53, []uint16{5}}, {1, 53, nil},
		{11, 53, []uint16{5}}, {7, 53, []uint16{1695}},
		{11, 53, []uint16{3}}, {5, 53, []uint16{1687}},
		{13, 53, []uint16{3, 1}}, {11, 53, []uint16{2}},
		{16, 53, nil}, {13, 54, []uint16{4, 1838}},
		{13, 54, []uint16{5}}, {1, 54, nil},
		{11, 54, []uint16{5}}, {16, 54, nil},
		{13, 54, []uint16{4, 1838}}, {13, 54, []uint16{5}},
		{1, 54, nil}, {11, 54, []uint16{5}},
		{16, 54, nil}, {13, 54, []uint16{4, 1838}},
		{13, 54, []uint16{5}}, {1, 54, nil},
		{11, 54, []uint16{5}}, {16, 54, nil},
		{13, 54, []uint16{1}}, {13, 54, []uint16{3, 1}},
		{13, 54, []uint16{2, 1697, 1702, 1707}}, {18, 54, []uint16{1720}},
		{1, 54, nil}, {4, 54, nil},
		{6, 54, []uint16{1720}}, {5, 54, []uint16{1715}},
		{11, 54, []uint16{2}}, {15, 54, nil},
		{16, 54, nil}, {13, 55, []uint16{1}},
		{8, 55, []uint16{31}}, {15, 55, nil},
		{16, 55, nil}, {13, 55, []uint16{4, 1842}},
		{13, 55, []uint16{5}}, {1, 55, nil},
		{11, 55, []uint16{5}}, {16, 55, nil},
		{13, 55, []uint16{4, 1842}}, {13, 55, []uint16{5}},
		{1, 55, nil}, {11, 55, []uint16{5}},
		{16, 55, nil}, {13, 55, []uint16{1}},
		{13, 55, []uint16{3, 1}}, {13, 55, []uint16{2, 1723, 1727, 1732}},
		{18, 55, []uint16{1745}}, {1, 55, nil},
		{4, 55, nil}, {6, 55, []uint16{1745}},
		{5, 55, []uint16{1740}}, {11, 55, []uint16{2}},
		{15, 55, nil}, {16, 55, nil},
		{13, 56, []uint16{1}}, {8, 56, []uint16{32}},
		{15, 56, nil}, {16, 56, nil},
		{13, 56, []uint16{4, 1842}}, {13, 56, []uint16{5}},
		{1, 56, nil}, {11, 56, []uint16{5}},
		{16, 56, nil}, {13, 56, []uint16{4, 1842}},
		{13, 56, []uint16{5}}, {1, 56, nil},
		{11, 56, []uint16{5}}, {16, 56, nil},
		{13, 56, []uint16{4, 1842}}, {13, 56, []uint16{5}},
		{1, 56, nil}, {11, 56, []uint16{5}},
		{16, 56, nil}, {13, 56, []uint16{4, 1842}},
		{13, 56, []uint16{5}}, {1, 56, nil},
		{11, 56, []uint16{5}}, {16, 56, nil},
		{13, 56, []uint16{4, 1842}}, {13, 56, []uint16{5}},
		{1, 56, nil}, {11, 56, []uint16{5}},
		{16, 56, nil}, {13, 56, []uint16{4, 1842}},
		{13, 56, []uint16{5}}, {1, 56, nil},
		{11, 56, []uint16{5}}, {16, 56, nil},
		{13, 56, []uint16{4, 1842}}, {13, 56, []uint16{5}},
		{1, 56, nil}, {11, 56, []uint16{5}},
		{16, 56, nil}, {13, 56, []uint16{4, 1842}},
		{13, 56, []uint16{5}}, {1, 56, nil},
		{11, 56, []uint16{5}}, {16, 56, nil},
		{13, 56, []uint16{1}}, {13, 56, []uint16{3, 1}},
		{13, 56, []uint16{2, 1748, 1752, 1757, 1762, 1767, 1772, 1777, 1782, 1787}}, {18, 56, []uint16{1800}},
		{1, 56, nil}, {4, 56, nil},
		{6, 56, []uint16{1800}}, {5, 56, []uint16{1795}},
		{11, 56, []uint16{2}}, {15, 56, nil},
		{16, 56, nil}, {13, 57, []uint16{1}},
		{8, 57, []uint16{33}}, {15, 57, nil},
		{16, 57, nil}, {13, 57, []uint16{4, 1842}},
		{13, 57, []uint16{5}}, {1, 57, nil},
		{11, 57, []uint16{5}}, {16, 57, nil},
		{13, 57, []uint16{4, 1842}}, {13, 57, []uint16{5}},
		{1, 57, nil}, {11, 57, []uint16{5}},
		{16, 57, nil}, {13, 57, []uint16{4, 1842}},
		{13, 57, []uint16{5}}, {1, 57, nil},
		{11, 57, []uint16{5}}, {16, 57, nil},
		{13, 57, []uint16{4, 1842}}, {13, 57, []uint16{5}},
		{1, 57, nil}, {11, 57, []uint16{5}},
		{16, 57, nil}, {13, 57, []uint16{1}},
		{13, 57, []uint16{3, 1}}, {13, 57, []uint16{2, 1803, 1807, 1812, 1817, 1822}},
		{18, 57, []uint16{1835}}, {1, 57, nil},
		{4, 57, nil}, {6, 57, []uint16{1835}},
		{5, 57, []uint16{1830}}, {11, 57, []uint16{2}},
		{15, 57, nil}, {16, 57, nil},
		{13, 58, []uint16{1}}, {8, 58, []uint16{34}},
		{15, 58, nil}, {16, 58, nil},
		{13, 59, []uint16{1}}, {8, 59, []uint16{35}},
		{15, 59, nil}, {16, 59, nil},
		{13, 32, []uint16{1}}, {8, 32, []uint16{36}},
		{15, 32, nil}, {16, 32, nil},
		{13, 32, []uint16{4, 1949}}, {13, 32, []uint16{5}},
		{1, 32, nil}, {11, 32, []uint16{5}},
		{16, 32, nil}, {13, 32, []uint16{4, 2028}},
		{13, 32, []uint16{5}}, {1, 32, nil},
		{11, 32, []uint16{5}}, {16, 32, nil},
		{13, 32, []uint16{1}}, {8, 32, []uint16{23}},
		{15, 32, nil}, {16, 32, nil},
		{13, 32, []uint16{4, 2107}}, {13, 32, []uint16{5}},
		{1, 32, nil}, {11, 32, []uint16{5}},
		{16, 32, nil}, {13, 32, []uint16{1}},
		{13, 32, []uint16{3, 1}}, {13, 32, []uint16{2, 1860, 1864}},
		{18, 32, []uint16{1877}}, {1, 32, nil},
		{4, 32, nil}, {6, 32, []uint16{1877}},
		{5, 32, []uint16{1872}}, {11, 32, []uint16{2}},
		{15, 32, nil}, {16, 32, nil},
		{13, 32, []uint16{2, 1850, 1855, 1869}}, {18, 32, []uint16{1888}},
		{13, 32, []uint16{5}}, {1, 32, nil},
		{11, 32, []uint16{5}}, {7, 32, []uint16{1889}},
		{11, 32, []uint16{3}}, {5, 32, []uint16{1881}},
		{13, 32, []uint16{3, 1}}, {11, 32, []uint16{2}},
		{16, 32, nil}, {13, 32, []uint16{3, 2}},
		{13, 32, []uint16{4, 1880}}, {13, 32, []uint16{5}},
		{1, 32, nil}, {11, 32, []uint16{5}},
		{12, 32, []uint16{1899}}, {4, 32, nil},
		{5, 32, []uint16{1892}}, {16, 32, nil},
		{13, 32, []uint16{1}}, {8, 32, []uint16{37}},
		{15, 32, nil}, {16, 32, nil},
		{13, 32, []uint16{1}}, {8, 32, []uint16{19}},
		{15, 32, nil}, {16, 32, nil},
		{13, 32, []uint16{4, 1904}}, {13, 32, []uint16{5}},
		{1, 32, nil}, {11, 32, []uint16{5}},
		{12, 32, []uint16{1914}}, {16, 32, nil},
		{13, 32, []uint16{3, 0}}, {16, 32, nil},
		{13, 32, []uint16{1}}, {13, 32, []uint16{3, 1}},
		{13, 32, []uint16{2, 1846, 1891, 1900, 1908}}, {18, 32, []uint16{1924}},
		{1, 32, nil}, {4, 32, nil},
		{6, 32, []uint16{1924}}, {5, 32, []uint16{1919}},
		{11, 32, []uint16{2}}, {15, 32, nil},
		{16, 32, nil}, {13, 32, []uint16{1}},
		{13, 32, []uint16{4, 1916}}, {1, 32, nil},
		{6, 32, []uint16{1933}}, {2, 32, []uint16{18}},
		{16, 32, nil}, {11, 32, []uint16{1}},
		{16, 32, nil}, {13, 60, []uint16{4, 2028}},
		{13, 60, []uint16{5}}, {1, 60, nil},
		{11, 60, []uint16{5}}, {16, 60, nil},
		{13, 60, []uint16{1}}, {8, 60, []uint16{38}},
		{15, 60, nil}, {16, 60, nil},
		{13, 60, []uint16{4, 2028}}, {13, 60, []uint16{5}},
		{1, 60, nil}, {11, 60, []uint16{5}},
		{16, 60, nil}, {13, 60, []uint16{1}},
		{13, 60, []uint16{3, 1}}, {13, 60, []uint16{2, 1935, 1940, 1944}},
		{18, 60, []uint16{1957}}, {1, 60, nil},
		{4, 60, nil}, {6, 60, []uint16{1957}},
		{5, 60, []uint16{1952}}, {11, 60, []uint16{2}},
		{15, 60, nil}, {16, 60, nil},
		{13, 61, []uint16{1}}, {8, 61, []uint16{37}},
		{15, 61, nil}, {16, 61, nil},
		{13, 61, []uint16{1}}, {8, 61, []uint16{23}},
		{15, 61, nil}, {16, 61, nil},
		{13, 61, []uint16{4, 2329}}, {13, 61, []uint16{5}},
		{1, 61, nil}, {11, 61, []uint16{5}},
		{16, 61, nil}, {13, 61, []uint16{2, 1960, 1964, 1968}},
		{18, 61, []uint16{1981}}, {13, 61, []uint16{5}},
		{1, 61, nil}, {11, 61, []uint16{5}},
		{7, 61, []uint16{1982}}, {11, 61, []uint16{3}},
		{5, 61, []uint16{1974}}, {13, 61, []uint16{3, 1}},
		{11, 61, []uint16{2}}, {16, 61, nil},
		{13, 61, []uint16{1}}, {13, 61, []uint16{4, 1973}},
		{13, 61, []uint16{5}}, {1, 61, nil},
		{11, 61, []uint16{5}}, {9, 61, nil},
		{14, 61, nil}, {16, 61, nil},
		{13, 61, []uint16{4, 971}}, {13, 61, []uint16{5}},
		{1, 61, nil}, {11, 61, []uint16{5}},
		{16, 61, nil}, {13, 61, []uint16{1}},
		{13, 61, []uint16{3, 1}}, {13, 61, []uint16{2, 1984, 1992}},
		{18, 61, []uint16{2005}}, {1, 61, nil},
		{4, 61, nil}, {6, 61, []uint16{2005}},
		{5, 61, []uint16{2000}}, {11, 61, []uint16{2}},
		{15, 61, nil}, {16, 61, nil},
		{13, 61, []uint16{1}}, {8, 61, []uint16{23}},
		{15, 61, nil}, {16, 61, nil},
		{13, 61, []uint16{4, 2052}}, {13, 61, []uint16{5}},
		{1, 61, nil}, {11, 61, []uint16{5}},
		{16, 61, nil}, {13, 61, []uint16{1}},
		{13, 61, []uint16{3, 1}}, {13, 61, []uint16{2, 2008, 2012}},
		{18, 61, []uint16{2025}}, {1, 61, nil},
		{4, 61, nil}, {6, 61, []uint16{2025}},
		{5, 61, []uint16{2020}}, {11, 61, []uint16{2}},
		{15, 61, nil}, {16, 61, nil},
		{13, 61, []uint16{2, 1997, 2017}}, {18, 61, []uint16{2036}},
		{13, 61, []uint16{5}}, {1, 61, nil},
		{11, 61, []uint16{5}}, {7, 61, []uint16{2037}},
		{11, 61, []uint16{3}}, {5, 61, []uint16{2029}},
		{13, 61, []uint16{3, 1}}, {11, 61, []uint16{2}},
		{16, 61, nil}, {13, 63, []uint16{1}},
		{8, 63, []uint16{37}}, {15, 63, nil},
		{16, 63, nil}, {13, 63, []uint16{1}},
		{8, 63, []uint16{39}}, {15, 63, nil},
		{16, 63, nil}, {13, 63, []uint16{4, 1643}},
		{13, 63, []uint16{5}}, {1, 63, nil},
		{11, 63, []uint16{5}}, {16, 63, nil},
		{13, 63, []uint16{2, 2039, 2043, 2047}}, {18, 63, []uint16{2060}},
		{13, 63, []uint16{5}}, {1, 63, nil},
		{11, 63, []uint16{5}}, {7, 63, []uint16{2061}},
		{11, 63, []uint16{3}}, {5, 63, []uint16{2053}},
		{13, 63, []uint16{3, 1}}, {11, 63, []uint16{2}},
		{16, 63, nil}, {13, 62, []uint16{1}},
		{8, 62, []uint16{40}}, {15, 62, nil},
		{16, 62, nil}, {13, 62, []uint16{4, 2118}},
		{13, 62, []uint16{5}}, {1, 62, nil},
		{11, 62, []uint16{5}}, {16, 62, nil},
		{13, 62, []uint16{1}}, {8, 62, []uint16{41}},
		{15, 62, nil}, {16, 62, nil},
		{13, 62, []uint16{4, 2126}}, {13, 62, []uint16{5}},
		{1, 62, nil}, {11, 62, []uint16{5}},
		{16, 62, nil}, {13, 62, []uint16{1}},
		{8, 62, []uint16{42}}, {15, 62, nil},
		{16, 62, nil}, {13, 62, []uint16{1}},
		{13, 62, []uint16{3, 1}}, {13, 62, []uint16{2, 2072, 2076, 2081}},
		{18, 62, []uint16{2093}}, {1, 62, nil},
		{4, 62, nil}, {6, 62, []uint16{2093}},
		{5, 62, []uint16{2088}}, {11, 62, []uint16{2}},
		{15, 62, nil}, {16, 62, nil},
		{13, 62, []uint16{2, 2067, 2085}}, {18, 62, []uint16{2104}},
		{13, 62, []uint16{5}}, {1, 62, nil},
		{11, 62, []uint16{5}}, {7, 62, []uint16{2105}},
		{11, 62, []uint16{3}}, {5, 62, []uint16{2097}},
		{13, 62, []uint16{3, 1}}, {11, 62, []uint16{2}},
		{16, 62, nil}, {13, 62, []uint16{1}},
		{13, 62, []uint16{3, 1}}, {13, 62, []uint16{2, 2063, 2096}},
		{18, 62, []uint16{2115}}, {1, 62, nil},
		{4, 62, nil}, {6, 62, []uint16{2115}},
		{5, 62, []uint16{2110}}, {11, 62, []uint16{2}},
		{15, 62, nil}, {16, 62, nil},
		{13, 64, []uint16{1}}, {8, 64, []uint16{43}},
		{15, 64, nil}, {16, 64, nil},
		{13, 65, []uint16{1}}, {8, 65, []uint16{17}},
		{15, 65, nil}, {16, 65, nil},
		{13, 65, []uint16{3, 1}}, {13, 65, []uint16{4, 2122}},
		{13, 65, []uint16{5}}, {1, 65, nil},
		{11, 65, []uint16{5}}, {12, 65, []uint16{2134}},
		{4, 65, nil}, {5, 65, []uint16{2127}},
		{16, 65, nil}, {13, 33, []uint16{1}},
		{8, 33, []uint16{44}}, {15, 33, nil},
		{16, 33, nil}, {13, 33, []uint16{1}},
		{13, 33, []uint16{4, 2135}}, {1, 33, nil},
		{6, 33, []uint16{2145}}, {2, 33, []uint16{19}},
		{16, 33, nil}, {11, 33, []uint16{1}},
		{16, 33, nil}, {13, 8, []uint16{1}},
		{8, 8, []uint16{41}}, {15, 8, nil},
		{16, 8, nil}, {13, 8, []uint16{4, 2251}},
		{13, 8, []uint16{5}}, {1, 8, nil},
		{11, 8, []uint16{5}}, {16, 8, nil},
		{13, 8, []uint16{1}}, {8, 8, []uint16{42}},
		{15, 8, nil}, {16, 8, nil},
		{13, 8, []uint16{1}}, {13, 8, []uint16{3, 1}},
		{13, 8, []uint16{2, 2147, 2151, 2156}}, {18, 8, []uint16{2168}},
		{1, 8, nil}, {4, 8, nil},
		{6, 8, []uint16{2168}}, {5, 8, []uint16{2163}},
		{11, 8, []uint16{2}}, {15, 8, nil},
		{16, 8, nil}, {13, 8, []uint16{1}},
		{13, 8, []uint16{4, 2160}}, {1, 8, nil},
		{6, 8, []uint16{2177}}, {2, 8, []uint16{20}},
		{16, 8, nil}, {11, 8, []uint16{1}},
		{16, 8, nil}, {13, 66, []uint16{1}},
		{8, 66, []uint16{45}}, {15, 66, nil},
		{16, 66, nil}, {13, 66, []uint16{1}},
		{13, 66, []uint16{4, 2179}}, {13, 66, []uint16{5}},
		{1, 66, nil}, {11, 66, []uint16{5}},
		{9, 66, nil}, {14, 66, nil},
		{16, 66, nil}, {13, 66, []uint16{4, 971}},
		{13, 66, []uint16{5}}, {1, 66, nil},
		{11, 66, []uint16{5}}, {16, 66, nil},
		{13, 66, []uint16{1}}, {13, 66, []uint16{3, 1}},
		{13, 66, []uint16{2, 2183, 2191}}, {18, 66, []uint16{2204}},
		{1, 66, nil}, {4, 66, nil},
		{6, 66, []uint16{2204}}, {5, 66, []uint16{2199}},
		{11, 66, []uint16{2}}, {15, 66, nil},
		{16, 66, nil}, {13, 66, []uint16{3, 1}},
		{13, 66, []uint16{4, 2196}}, {13, 66, []uint16{5}},
		{1, 66, nil}, {11, 66, []uint16{5}},
		{12, 66, []uint16{2215}}, {4, 66, nil},
		{5, 66, []uint16{2208}}, {16, 66, nil},
		{13, 66, []uint16{1}}, {8, 66, []uint16{41}},
		{15, 66, nil}, {16, 66, nil},
		{13, 66, []uint16{4, 2251}}, {13, 66, []uint16{5}},
		{1, 66, nil}, {11, 66, []uint16{5}},
		{16, 66, nil}, {13, 66, []uint16{1}},
		{8, 66, []uint16{42}}, {15, 66, nil},
		{16, 66, nil}, {13, 66, []uint16{1}},
		{13, 66, []uint16{3, 1}}, {13, 66, []uint16{2, 2216, 2220, 2225}},
		{18, 66, []uint16{2237}}, {1, 66, nil},
		{4, 66, nil}, {6, 66, []uint16{2237}},
		{5, 66, []uint16{2232}}, {11, 66, []uint16{2}},
		{15, 66, nil}, {16, 66, nil},
		{13, 66, []uint16{2, 2207, 2229}}, {18, 66, []uint16{2248}},
		{13, 66, []uint16{5}}, {1, 66, nil},
		{11, 66, []uint16{5}}, {7, 66, []uint16{2249}},
		{11, 66, []uint16{3}}, {5, 66, []uint16{2241}},
		{13, 66, []uint16{3, 1}}, {11, 66, []uint16{2}},
		{16, 66, nil}, {13, 66, []uint16{3, 2}},
		{13, 66, []uint16{4, 2240}}, {13, 66, []uint16{5}},
		{1, 66, nil}, {11, 66, []uint16{5}},
		{12, 66, []uint16{2259}}, {4, 66, nil},
		{5, 66, []uint16{2252}}, {16, 66, nil},
		{13, 1, []uint16{4, 2325}}, {13, 1, []uint16{5}},
		{1, 1, nil}, {11, 1, []uint16{5}},
		{16, 1, nil}, {13, 1, []uint16{4, 2329}},
		{13, 1, []uint16{5}}, {1, 1, nil},
		{11, 1, []uint16{5}}, {16, 1, nil},
		{13, 1, []uint16{4, 985}}, {13, 1, []uint16{5}},
		{1, 1, nil}, {11, 1, []uint16{5}},
		{16, 1, nil}, {13, 1, []uint16{2, 2260, 2265, 2270}},
		{18, 1, []uint16{2283}}, {13, 1, []uint16{5}},
		{1, 1, nil}, {11, 1, []uint16{5}},
		{7, 1, []uint16{2284}}, {11, 1, []uint16{3}},
		{5, 1, []uint16{2276}}, {13, 1, []uint16{3, 1}},
		{11, 1, []uint16{2}}, {16, 1, nil},
		{13, 1, []uint16{3, 2}}, {13, 1, []uint16{4, 2275}},
		{13, 1, []uint16{5}}, {1, 1, nil},
		{11, 1, []uint16{5}}, {12, 1, []uint16{2294}},
		{4, 1, nil}, {5, 1, []uint16{2287}},
		{16, 1, nil}, {13, 68, []uint16{4, 2325}},
		{13, 68, []uint16{5}}, {1, 68, nil},
		{11, 68, []uint16{5}}, {16, 68, nil},
		{13, 68, []uint16{4, 1113}}, {13, 68, []uint16{5}},
		{1, 68, nil}, {11, 68, []uint16{5}},
		{16, 68, nil}, {13, 68, []uint16{2, 2295, 2300}},
		{18, 68, []uint16{2313}}, {13, 68, []uint16{5}},
		{1, 68, nil}, {11, 68, []uint16{5}},
		{7, 68, []uint16{2314}}, {11, 68, []uint16{3}},
		{5, 68, []uint16{2306}}, {13, 68, []uint16{3, 1}},
		{11, 68, []uint16{2}}, {16, 68, nil},
		{13, 68, []uint16{3, 2}}, {13, 68, []uint16{4, 2305}},
		{13, 68, []uint16{5}}, {1, 68, nil},
		{11, 68, []uint16{5}}, {12, 68, []uint16{2324}},
		{4, 68, nil}, {5, 68, []uint16{2317}},
		{16, 68, nil}, {13, 67, []uint16{1}},
		{8, 67, []uint16{46}}, {15, 67, nil},
		{16, 67, nil}, {13, 42, []uint16{1}},
		{8, 42, []uint16{47}}, {15, 42, nil},
		{16, 42, nil}, {13, 9, []uint16{4, 2286}},
		{13, 9, []uint16{5}}, {1, 9, nil},
		{11, 9, []uint16{5}}, {16, 9, nil},
		{13, 9, []uint16{1}}, {8, 9, []uint16{48}},
		{15, 9, nil}, {16, 9, nil},
		{13, 9, []uint16{1}}, {13, 9, []uint16{3, 1}},
		{13, 9, []uint16{2, 2333, 2338}}, {18, 9, []uint16{2350}},
		{1, 9, nil}, {4, 9, nil},
		{6, 9, []uint16{2350}}, {5, 9, []uint16{2345}},
		{11, 9, []uint16{2}}, {15, 9, nil},
		{16, 9, nil}, {13, 9, []uint16{4, 2316}},
		{13, 9, []uint16{5}}, {1, 9, nil},
		{11, 9, []uint16{5}}, {16, 9, nil},
		{13, 9, []uint16{4, 1166}}, {13, 9, []uint16{5}},
		{1, 9, nil}, {11, 9, []uint16{5}},
		{16, 9, nil}, {13, 9, []uint16{4, 2358}},
		{13, 9, []uint16{5}}, {1, 9, nil},
		{11, 9, []uint16{5}}, {12, 9, []uint16{2369}},
		{16, 9, nil}, {13, 9, []uint16{3, 0}},
		{16, 9, nil}, {13, 9, []uint16{4, 2329}},
		{13, 9, []uint16{5}}, {1, 9, nil},
		{11, 9, []uint16{5}}, {16, 9, nil},
		{13, 9, []uint16{1}}, {13, 9, []uint16{3, 1}},
		{13, 9, []uint16{2, 2353, 2363, 2371}}, {18, 9, []uint16{2384}},
		{1, 9, nil}, {4, 9, nil},
		{6, 9, []uint16{2384}}, {5, 9, []uint16{2379}},
		{11, 9, []uint16{2}}, {15, 9, nil},
		{16, 9, nil}, {13, 9, []uint16{4, 2286}},
		{13, 9, []uint16{5}}, {1, 9, nil},
		{11, 9, []uint16{5}}, {16, 9, nil},
		{13, 9, []uint16{4, 2423}}, {13, 9, []uint16{5}},
		{1, 9, nil}, {11, 9, []uint16{5}},
		{16, 9, nil}, {13, 9, []uint16{1}},
		{13, 9, []uint16{3, 1}}, {13, 9, []uint16{2, 2387, 2392}},
		{18, 9, []uint16{2405}}, {1, 9, nil},
		{4, 9, nil}, {6, 9, []uint16{2405}},
		{5, 9, []uint16{2400}}, {11, 9, []uint16{2}},
		{15, 9, nil}, {16, 9, nil},
		{13, 9, []uint16{2, 2342, 2376, 2397}}, {18, 9, []uint16{2416}},
		{13, 9, []uint16{5}}, {1, 9, nil},
		{11, 9, []uint16{5}}, {7, 9, []uint16{2417}},
		{11, 9, []uint16{3}}, {5, 9, []uint16{2409}},
		{13, 9, []uint16{3, 1}}, {11, 9, []uint16{2}},
		{16, 9, nil}, {13, 6, []uint16{1}},
		{8, 6, []uint16{13}}, {15, 6, nil},
		{16, 6, nil}, {13, 6, []uint16{1}},
		{13, 6, []uint16{4, 2419}}, {13, 6, []uint16{5}},
		{1, 6, nil}, {11, 6, []uint16{5}},
		{9, 6, nil}, {14, 6, nil},
		{16, 6, nil},
	},
	ss: []string{
		"Grammar", "__", "initializer",
		"Initializer", "rules", "Rule",
		"EOF", "code", "CodeBlock",
		"EOS", "name", "IdentifierName",
		"display", "StringLiteral", "RuleDefOp",
		"expr", "Expression", "ChoiceExpr",
		"first", "ActionExpr", "rest",
		"SeqExpr", "LabeledExpr", "label",
		"Identifier", "PrefixedExpr", "op",
		"PrefixedOp", "SuffixedExpr", "PrimaryExpr",
		"SuffixedOp", "LitMatcher", "CharClassMatcher",
		"AnyMatcher", "RuleRefExpr", "SemanticPredExpr",
		"SemanticPredOp", "SourceChar", "Comment",
		"MultiLineComment", "SingleLineComment", "MultiLineCommentNoLineTerminator",
		"EOL", "IdentifierStart", "IdentifierPart",
		"lit", "ignore", "DoubleStringChar",
		"SingleStringChar", "RawStringChar", "DoubleStringEscape",
		"SingleStringEscape", "CommonEscapeSequence", "SingleCharEscape",
		"OctalEscape", "HexEscape", "LongUnicodeEscape",
		"ShortUnicodeEscape", "OctalDigit", "HexDigit",
		"ClassCharRange", "ClassChar", "UnicodeClassEscape",
		"CharClassEscape", "SingleCharUnicodeClass", "UnicodeClass",
		"Code", "Whitespace", "_",
	},
	ms: []ϡmatcher{
		ϡstringMatcher{
			ignoreCase: false,
			value:      "/",
		},
		ϡstringMatcher{
			ignoreCase: false,
			value:      ":",
		},
		ϡstringMatcher{
			ignoreCase: false,
			value:      "&",
		},
		ϡstringMatcher{
			ignoreCase: false,
			value:      "!",
		},
		ϡstringMatcher{
			ignoreCase: false,
			value:      "?",
		},
		ϡstringMatcher{
			ignoreCase: false,
			value:      "*",
		},
		ϡstringMatcher{
			ignoreCase: false,
			value:      "+",
		},
		ϡstringMatcher{
			ignoreCase: false,
			value:      "(",
		},
		ϡstringMatcher{
			ignoreCase: false,
			value:      ")",
		},
		ϡstringMatcher{
			ignoreCase: false,
			value:      "=",
		},
		ϡstringMatcher{
			ignoreCase: false,
			value:      "<-",
		},
		ϡstringMatcher{
			ignoreCase: false,
			value:      "←",
		},
		ϡstringMatcher{
			ignoreCase: false,
			value:      "⟵",
		},
		ϡanyMatcher{},
		ϡstringMatcher{
			ignoreCase: false,
			value:      "/*",
		},
		ϡstringMatcher{
			ignoreCase: false,
			value:      "*/",
		},
		ϡstringMatcher{
			ignoreCase: false,
			value:      "//",
		},
		ϡcharClassMatcher{
			ignoreCase: true,
			inverted:   false,
			chars:      []rune{'_'},
			ranges:     []rune{'a', 'z'},
			classes:    []*unicode.RangeTable{},
		},
		ϡcharClassMatcher{
			ignoreCase: false,
			inverted:   false,
			chars:      []rune{},
			ranges:     []rune{'0', '9'},
			classes:    []*unicode.RangeTable{},
		},
		ϡstringMatcher{
			ignoreCase: false,
			value:      "i",
		},
		ϡstringMatcher{
			ignoreCase: false,
			value:      "\"",
		},
		ϡstringMatcher{
			ignoreCase: false,
			value:      "'",
		},
		ϡstringMatcher{
			ignoreCase: false,
			value:      "`",
		},
		ϡstringMatcher{
			ignoreCase: false,
			value:      "\\",
		},
		ϡstringMatcher{
			ignoreCase: false,
			value:      "a",
		},
		ϡstringMatcher{
			ignoreCase: false,
			value:      "b",
		},
		ϡstringMatcher{
			ignoreCase: false,
			value:      "n",
		},
		ϡstringMatcher{
			ignoreCase: false,
			value:      "f",
		},
		ϡstringMatcher{
			ignoreCase: false,
			value:      "r",
		},
		ϡstringMatcher{
			ignoreCase: false,
			value:      "t",
		},
		ϡstringMatcher{
			ignoreCase: false,
			value:      "v",
		},
		ϡstringMatcher{
			ignoreCase: false,
			value:      "x",
		},
		ϡstringMatcher{
			ignoreCase: false,
			value:      "U",
		},
		ϡstringMatcher{
			ignoreCase: false,
			value:      "u",
		},
		ϡcharClassMatcher{
			ignoreCase: false,
			inverted:   false,
			chars:      []rune{},
			ranges:     []rune{'0', '7'},
			classes:    []*unicode.RangeTable{},
		},
		ϡcharClassMatcher{
			ignoreCase: true,
			inverted:   false,
			chars:      []rune{},
			ranges:     []rune{'0', '9', 'a', 'f'},
			classes:    []*unicode.RangeTable{},
		},
		ϡstringMatcher{
			ignoreCase: false,
			value:      "[",
		},
		ϡstringMatcher{
			ignoreCase: false,
			value:      "]",
		},
		ϡstringMatcher{
			ignoreCase: false,
			value:      "-",
		},
		ϡstringMatcher{
			ignoreCase: false,
			value:      "^",
		},
		ϡstringMatcher{
			ignoreCase: false,
			value:      "p",
		},
		ϡstringMatcher{
			ignoreCase: false,
			value:      "{",
		},
		ϡstringMatcher{
			ignoreCase: false,
			value:      "}",
		},
		ϡcharClassMatcher{
			ignoreCase: false,
			inverted:   false,
			chars:      []rune{'L', 'M', 'N', 'C', 'P', 'Z', 'S'},
			ranges:     []rune{},
			classes:    []*unicode.RangeTable{},
		},
		ϡstringMatcher{
			ignoreCase: false,
			value:      ".",
		},
		ϡcharClassMatcher{
			ignoreCase: false,
			inverted:   false,
			chars:      []rune{'{', '}'},
			ranges:     []rune{},
			classes:    []*unicode.RangeTable{},
		},
		ϡcharClassMatcher{
			ignoreCase: false,
			inverted:   false,
			chars:      []rune{' ', '\t', '\r'},
			ranges:     []rune{},
			classes:    []*unicode.RangeTable{},
		},
		ϡstringMatcher{
			ignoreCase: false,
			value:      "\n",
		},
		ϡstringMatcher{
			ignoreCase: false,
			value:      ";",
		},
	},
	as: []func(*ϡvm) (interface{}, error){
		(*ϡvm).callOnGrammar1,
		(*ϡvm).callOnInitializer1,
		(*ϡvm).callOnRule1,
		(*ϡvm).callOnChoiceExpr1,
		(*ϡvm).callOnActionExpr1,
		(*ϡvm).callOnSeqExpr1,
		(*ϡvm).callOnLabeledExpr2,
		(*ϡvm).callOnPrefixedExpr2,
		(*ϡvm).callOnPrefixedOp1,
		(*ϡvm).callOnSuffixedExpr2,
		(*ϡvm).callOnSuffixedOp1,
		(*ϡvm).callOnPrimaryExpr7,
		(*ϡvm).callOnRuleRefExpr1,
		(*ϡvm).callOnSemanticPredExpr1,
		(*ϡvm).callOnSemanticPredOp1,
		(*ϡvm).callOnIdentifierName1,
		(*ϡvm).callOnLitMatcher1,
		(*ϡvm).callOnStringLiteral1,
		(*ϡvm).callOnCharClassMatcher1,
		(*ϡvm).callOnAnyMatcher1,
		(*ϡvm).callOnCodeBlock1,
	},
	bs: []func(*ϡvm) (bool, error){},
}

//+pigeon: err.go

var (
	// errInvalidEncoding is returned when the source is not properly
	// utf8-encoded.
	errInvalidEncoding = errors.New("invalid encoding")

	// errNoMatch is returned if no match could be found and no other
	// error has been raised.
	errNoMatch = errors.New("no match found")
)

// errList cumulates the errors found by the parser. It is part
// of the supported API.
type errList []error

// ϡadd adds err to the list of errors.
func (e *errList) ϡadd(err error) {
	if err != nil {
		*e = append(*e, err)
	}
}

// ϡerr returns the error list as an error, or nil if the list is empty.
func (e errList) ϡerr() error {
	if len(e) == 0 {
		return nil
	}
	e.ϡdedupe()
	return e
}

// ϡdedupe removes duplicate error messages from the list.
func (e *errList) ϡdedupe() {
	var cleaned []error
	set := make(map[string]bool)
	for _, err := range *e {
		if msg := err.Error(); !set[msg] {
			set[msg] = true
			cleaned = append(cleaned, err)
		}
	}
	*e = cleaned
}

// Error returns the error message for the errList. It implements the
// error interface.
func (e errList) Error() string {
	var buf bytes.Buffer

	for i, err := range e {
		if i > 0 {
			buf.WriteRune('\n')
		}
		buf.WriteString(err.Error())
	}
	return buf.String()
}

// parserError wraps an error with a prefix indicating the rule in which
// the error occurred. The original error is stored in the Inner field.
// It is part of the supported API.
type parserError struct {
	Inner   error
	ϡpos    position
	ϡprefix string
}

// Error returns the prefixed error message. It implements the error
// interface.
func (p *parserError) Error() string {
	return p.ϡprefix + ": " + p.Inner.Error()
}

//+pigeon: matchers.go

// ϡpeekReader is the interface that defines the peek and read
// methods.
type ϡpeekReader interface {
	peek() rune
	read()
}

// ϡmatcher is the interface that defines the match method.
type ϡmatcher interface {
	match(ϡpeekReader) bool
}

// ϡanyMatcher is a matcher that matches any character but the
// EOF.
type ϡanyMatcher struct{}

// match tries to match a character in the peekReader.
func (a ϡanyMatcher) match(pr ϡpeekReader) bool {
	rn := pr.peek()
	pr.read()
	return rn != utf8.RuneError
}

func (a ϡanyMatcher) String() string {
	return "."
}

// ϡstringMatcher is a matcher that matches a string.
type ϡstringMatcher struct {
	ignoreCase bool
	value      string // value must be lowercase if ignoreCase is true
}

// match tries to match the string in the peekReader.
func (s ϡstringMatcher) match(pr ϡpeekReader) bool {
	for _, want := range s.value {
		rn := pr.peek()
		if s.ignoreCase {
			rn = unicode.ToLower(rn)
		}
		if rn != want {
			return false
		}
		pr.read()
	}
	return true
}

func (s ϡstringMatcher) String() string {
	v := strconv.Quote(s.value)
	if s.ignoreCase {
		v += "i"
	}
	return v
}

// ϡcharClassMatcher is a matcher that matches classes of characters.
type ϡcharClassMatcher struct {
	chars   []rune // runes must be lowercase if ignoreCase is true
	ranges  []rune // same for ranges
	classes []*unicode.RangeTable

	ignoreCase bool
	inverted   bool
}

func (c ϡcharClassMatcher) String() string {
	var buf bytes.Buffer

	buf.WriteString("[")
	if c.inverted {
		buf.WriteString("^")
	}
	for _, c := range c.chars {
		buf.WriteRune(c)
	}
	for i := 0; i < len(c.ranges); i += 2 {
		buf.WriteString(fmt.Sprintf("%c-%c", c.ranges[i], c.ranges[i+1]))
	}
	// unicode classes can't be stringified
	if l := len(c.classes); l > 0 {
		buf.WriteString(fmt.Sprintf("\\p{%d classes}", l))
	}
	buf.WriteString("]")
	if c.ignoreCase {
		buf.WriteString("i")
	}
	return buf.String()
}

// match tries to match classes of characters in the peekReader.
func (c ϡcharClassMatcher) match(pr ϡpeekReader) bool {
	rn := pr.peek()
	pr.read()

	if c.ignoreCase {
		rn = unicode.ToLower(rn)
	}

	// try to match in the list of available chars
	for _, ch := range c.chars {
		if rn == ch {
			return !c.inverted
		}
	}

	// try to match in the list of ranges
	for i := 0; i < len(c.ranges); i += 2 {
		if rn >= c.ranges[i] && rn <= c.ranges[i+1] {
			return !c.inverted
		}
	}

	// try to match in the list of Unicode classes
	for _, cl := range c.classes {
		if unicode.Is(cl, rn) {
			return !c.inverted
		}
	}

	return c.inverted
}

// ϡrangeTable returns the corresponding unicode range table from the
// provided class name.
func ϡrangeTable(class string) *unicode.RangeTable {
	if rt, ok := unicode.Categories[class]; ok {
		return rt
	}
	if rt, ok := unicode.Properties[class]; ok {
		return rt
	}
	if rt, ok := unicode.Scripts[class]; ok {
		return rt
	}

	// cannot happen
	panic(fmt.Sprintf("invalid Unicode class: %s", class))
}

//+pigeon: ops.go

// ϡop represents an opcode.
type ϡop byte

// list of opcodes in the pigeon VM.
const (
	ϡopExit ϡop = iota
	ϡopCall
	ϡopCallA
	ϡopCallB
	ϡopCumulOrF
	ϡopJump
	ϡopJumpIfF
	ϡopJumpIfT
	ϡopMatch
	ϡopNilIfF
	ϡopNilIfT
	ϡopPop
	ϡopPopVJumpIfF
	ϡopPush
	ϡopRestore
	ϡopRestoreIfF
	ϡopReturn
	ϡopStoreIfT
	ϡopTakeLOrJump
	ϡopmax // must always be after the last valid opcode

	// ϡopPlaceholder is an (invalid) opcode used by the Generator
	// to insert opcodes that need the index of the starting instruction
	// of a rule that hasn't been generated yet.
	//
	// It must be placed after ϡopmax (because it is invalid in the
	// final program) and it has one argument, the index in the strings
	// array of the identifier of the rule.
	ϡopPlaceholder
)

// ϡlookupOp translates an opcode to a string.
var ϡlookupOp = []string{
	ϡopExit: "exit", ϡopCall: "call", ϡopCallA: "callA",
	ϡopCallB: "callB", ϡopCumulOrF: "cumulOrF",
	ϡopJump: "jump", ϡopJumpIfF: "jumpIfF", ϡopJumpIfT: "jumpIfT",
	ϡopMatch: "match", ϡopNilIfF: "nilIfF", ϡopNilIfT: "nilIfT",
	ϡopPop: "pop", ϡopPopVJumpIfF: "popVJumpIfF",
	ϡopPush: "push", ϡopRestore: "restore", ϡopRestoreIfF: "restoreIfF",
	ϡopReturn: "return", ϡopStoreIfT: "storeIfT", ϡopTakeLOrJump: "takeLOrJump",
}

// String returns the string representation of the opcode.
func (op ϡop) String() string {
	if 0 <= op && int(op) < len(ϡlookupOp) {
		return ϡlookupOp[op]
	}
	return "ϡop(" + strconv.Itoa(int(op)) + ")"
}

// ϡinstr holds a single instruction: an opcode with its arguments.
type ϡinstr struct {
	op       ϡop
	ruleNmIx int // because bootstrap instructions have rule index -1
	args     []uint16
}

// String returns the string representation of the instruction.
func (ins ϡinstr) String() string {
	var buf bytes.Buffer

	buf.WriteString("{" + strconv.Itoa(int(ins.op)) + ", " +
		strconv.Itoa(int(ins.ruleNmIx)) + ", ")

	if len(ins.args) > 0 {
		buf.WriteString("[]uint16{")
		for i, arg := range ins.args {
			if i > 0 {
				buf.WriteString(", ")
			}
			buf.WriteString(strconv.Itoa(int(arg)))
		}
		buf.WriteString("}")
	} else {
		buf.WriteString("nil")
	}

	buf.WriteString("}")
	return buf.String()
}

//+pigeon: parser.go

// position records a position in the text. It is part of the supported
// API.
type position struct {
	// line is the 1-based index of the line of the current rune.
	line int
	// col is the 1-based index of the current rune on the line.
	col int
	// offset is the 0-based index of the starting byte of the current rune.
	offset int
}

// String formats a position as a string.
func (p position) String() string {
	return fmt.Sprintf("%d:%d (%d)", p.line, p.col, p.offset)
}

// current represents current matching data. It is the value on which
// action and predicate code blocks are generated as methods. It is
// part of the supported API.
type current struct {
	// pos holds the start position of the current match.
	pos position
	// text contains the raw text of the match. It is a slice in the
	// source data, so it should not be modified.
	text []byte
}

// ϡsvpt stores all state required to go back to a point in the
// parser.
type ϡsvpt struct {
	position
	rn rune
	w  int
}

// ϡparser parses the input text as rune code points.
type ϡparser struct {
	data []byte
	pt   ϡsvpt
	cur  current
}

// peek returns the current rune.
func (p *ϡparser) peek() rune {
	return p.pt.rn
}

// read advances the parser to the next rune.
func (p *ϡparser) read() {
	p.pt.offset += p.pt.w
	rn, n := utf8.DecodeRune(p.data[p.pt.offset:])
	p.pt.rn = rn
	p.pt.w = n

	if rn == utf8.RuneError {
		if n > 0 {
			panic(errInvalidEncoding)
		}
	} else {
		p.pt.col++
		if rn == '\n' {
			p.pt.line++
			p.pt.col = 0
		}
	}
}

// sliceFrom gets the slice of bytes from the start savepoint to
// the current position, non inclusive.
func (p *ϡparser) sliceFrom(start ϡsvpt) []byte {
	return p.data[start.position.offset:p.pt.position.offset]
}

//+pigeon: pub.go

// Option is a function that can set an option on the parser. It returns
// the previous setting as an Option.
type Option func(*ϡvm) Option

// Debug creates an Option to set the debug flag to b. When set to true,
// debugging information is printed to stdout while parsing.
//
// The default is false.
func Debug(b bool) Option {
	return func(v *ϡvm) Option {
		old := v.debug
		v.debug = b
		return Debug(old)
	}
}

// Memoize creates an Option to set the memoize flag to b. When set to true,
// the parser will cache all results so each expression is evaluated only
// once. This guarantees linear parsing time even for pathological cases,
// at the expense of more memory and slower times for typical cases.
//
// The default is false.
func Memoize(b bool) Option {
	return func(v *ϡvm) Option {
		old := v.memoize
		v.memoize = b
		return Memoize(old)
	}
}

// Recover creates an Option to set the recover flag to b. When set to
// true, this causes the parser to recover from panics and convert it
// to an error. Setting it to false can be useful while debugging to
// access the full stack trace.
//
// The default is true.
func Recover(b bool) Option {
	return func(v *ϡvm) Option {
		old := v.recover
		v.recover = b
		return Recover(old)
	}
}

// ParseFile parses the file identified by filename.
func ParseFile(filename string, opts ...Option) (interface{}, error) {
	f, err := os.Open(filename)
	if err != nil {
		return nil, err
	}
	defer f.Close()
	return ParseReader(filename, f, opts...)
}

// ParseReader parses the data from r using filename as information in the
// error messages.
func ParseReader(filename string, r io.Reader, opts ...Option) (interface{}, error) {
	b, err := ioutil.ReadAll(r)
	if err != nil {
		return nil, err
	}

	return Parse(filename, b, opts...)
}

// Parse parses the data from b using filename as information in the
// error messages.
func Parse(filename string, b []byte, opts ...Option) (interface{}, error) {
	p := &ϡparser{
		data: b,
		pt:   ϡsvpt{position: position{line: 1}},
	}
	v := &ϡvm{
		filename: filename,
		parser:   p,
		recover:  true,
	}
	return v.setOptions(opts).run(ϡtheProgram)
}

//+pigeon: stacks.go

// ϡpstack implements the Position stack. It stores savepoints.
type ϡpstack struct {
	ar []ϡsvpt
	sp int
}

// push adds a value on the stack.
func (p *ϡpstack) push(pt ϡsvpt) {
	if p.sp >= len(p.ar) {
		p.ar = append(p.ar, pt)
	} else {
		p.ar[p.sp] = pt
	}
	p.sp++
}

// pop removes a value from the stack.
func (p *ϡpstack) pop() ϡsvpt {
	p.sp--
	return p.ar[p.sp]
}

func (p *ϡpstack) len() int {
	return p.sp
}

func newPstack(cap int) *ϡpstack {
	return &ϡpstack{ar: make([]ϡsvpt, cap)}
}

// ϡistack implements the Instruction index stack. It stores integers.
type ϡistack struct {
	ar []uint16
	sp int
}

// push adds a value on the stack.
func (i *ϡistack) push(v uint16) {
	if i.sp >= len(i.ar) {
		i.ar = append(i.ar, v)
	} else {
		i.ar[i.sp] = v
	}
	i.sp++
}

// pop removes a value from the stack.
func (i *ϡistack) pop() uint16 {
	i.sp--
	return i.ar[i.sp]
}

func (i *ϡistack) len() int {
	return i.sp
}

func newIstack(cap int) *ϡistack {
	return &ϡistack{ar: make([]uint16, cap)}
}

// ϡvstack implements the Value stack. It stores empty interfaces.
type ϡvstack struct {
	ar []interface{}
	sp int
}

// push adds a value on the stack.
func (v *ϡvstack) push(i interface{}) {
	if v.sp >= len(v.ar) {
		v.ar = append(v.ar, i)
	} else {
		v.ar[v.sp] = i
	}
	v.sp++
}

// pop removes a value from the stack.
func (v *ϡvstack) pop() interface{} {
	v.sp--
	return v.ar[v.sp]
}

// peek returns the value at the top of the stack, leaving it there.
func (v *ϡvstack) peek() interface{} {
	return v.ar[v.sp-1]
}

func (v *ϡvstack) len() int {
	return v.sp
}

func newVstack(cap int) *ϡvstack {
	return &ϡvstack{ar: make([]interface{}, cap)}
}

// ϡlstack implements the Loop stack. It stores slices of integers.
type ϡlstack struct {
	ar [][]uint16
	sp int
}

// push adds a value on the stack.
func (l *ϡlstack) push(a []uint16) {
	if l.sp >= len(l.ar) {
		l.ar = append(l.ar, a)
	} else {
		l.ar[l.sp] = a
	}
	l.sp++
}

// pop removes a value from the stack.
func (l *ϡlstack) pop() []uint16 {
	l.sp--
	return l.ar[l.sp]
}

// take removes the integer at index 0 from the slice at the top of the
// stack. It returns -1 if the slice is empty. The slice is left on the
// stack.
func (l *ϡlstack) take() int {
	v := -1
	a := l.ar[l.sp-1]
	if len(a) > 0 {
		v = int(a[0])
		l.ar[l.sp-1] = a[1:]
	}
	return v
}

func (l *ϡlstack) len() int {
	return l.sp
}

func newLstack(cap int) *ϡlstack {
	return &ϡlstack{ar: make([][]uint16, cap)}
}

// ϡargsSet holds the list of arguments (key and value) to pass
// to the code blocks.
type ϡargsSet map[string]interface{}

// ϡastack is a stack of ϡargsSet.
type ϡastack struct {
	ar []ϡargsSet
	sp int
}

// push adds an empty ϡargsSet on top of the stack.
func (a *ϡastack) push() {
	if a.sp >= len(a.ar) {
		a.ar = append(a.ar, nil)
	} else {
		a.ar[a.sp] = nil
	}
	a.sp++
}

// pop removes the top ϡargsSet from the stack.
func (a *ϡastack) pop() {
	a.sp--
}

// peek returns the current top ϡargsSet.
func (a *ϡastack) peek() ϡargsSet {
	as := a.ar[a.sp-1]
	if as == nil {
		as = make(ϡargsSet)
		a.ar[a.sp-1] = as
	}
	return as
}

func (a *ϡastack) len() int {
	return a.sp
}

func newAstack(cap int) *ϡastack {
	return &ϡastack{ar: make([]ϡargsSet, cap)}
}

//+pigeon: vm.go

// ϡsentinel is a type used to define sentinel values that shouldn't
// be equal to something else.
type ϡsentinel int

const (
	// ϡmatchFailed is a sentinel value used to indicate a match failure.
	ϡmatchFailed ϡsentinel = iota - 1
)

const (
	// stack IDs, used in PUSH and POP's first argument
	ϡpstackID = iota + 1
	ϡlstackID
	ϡvstackID
	ϡistackID
	ϡastackID

	// special V stack values
	ϡvValNil    uint16 = 0
	ϡvValFailed uint16 = 1
	ϡvValEmpty  uint16 = 2
)

var (
	ϡstackNm = []string{
		ϡpstackID: "P",
		ϡlstackID: "L",
		ϡvstackID: "V",
		ϡistackID: "I",
		ϡastackID: "A",
	}
)

// special values that may be pushed on the V stack.
var ϡvSpecialValues = []interface{}{
	nil,
	ϡmatchFailed,
	[]interface{}(nil),
}

type ϡmemoizedResult struct {
	v  interface{}
	pt ϡsvpt
}

// ϡprogram is the data structure that is generated by the builder
// based on an input PEG. It contains the program information required
// to execute the grammar using the vm.
type ϡprogram struct {
	instrs []ϡinstr

	// lists
	ms []ϡmatcher
	as []func(*ϡvm) (interface{}, error)
	bs []func(*ϡvm) (bool, error)
	ss []string
}

// String formats the program's instructions in a human-readable format.
func (pg ϡprogram) String() string {
	var buf bytes.Buffer

	for i, instr := range pg.instrs {
		buf.WriteString(fmt.Sprintf("[%3d]: %s\n", i, pg.instrToString(instr)))
	}
	return buf.String()
}

// instrToString formats an instruction in a human-readable format, in the
// context of the program.
func (pg ϡprogram) instrToString(instr ϡinstr) string {
	var buf bytes.Buffer

	rule := pg.ruleNameAt(instr.ruleNmIx)
	if rule == "" {
		rule = "<bootstrap>"
	}
	buf.WriteString(fmt.Sprintf("%s.%s %v", rule, instr.op, instr.args))
	switch instr.op {
	case ϡopPush, ϡopPop:
		buf.WriteString(" " + ϡstackNm[instr.args[0]])
	case ϡopMatch:
		buf.WriteString(fmt.Sprintf(" %s", pg.ms[instr.args[0]]))
	case ϡopStoreIfT:
		buf.WriteString(" " + pg.ss[instr.args[0]])
	}
	return buf.String()
}

// ruleNameAt returns the name of the rule that contains the instruction
// index. It returns an empty string is the instruction is not part of a
// rule (bootstrap instruction, invalid index).
func (pg ϡprogram) ruleNameAt(ix int) string {
	if ix < 0 || ix >= len(pg.ss) {
		return ""
	}
	return pg.ss[ix]
}

// ϡvm holds the state to execute a compiled grammar.
type ϡvm struct {
	// input
	filename string
	parser   *ϡparser

	// options
	debug   bool
	memoize bool
	recover bool

	// program data
	pc  uint16
	pg  *ϡprogram
	cur current

	// stacks
	p *ϡpstack
	l *ϡlstack
	v *ϡvstack
	i *ϡistack
	a *ϡastack

	// TODO: memoization...
	// TODO: farthest failure position

	// error list
	errs errList
}

// setOptions applies the options in sequence on the vm. It returns the
// vm to allow for chaining calls.
func (v *ϡvm) setOptions(opts []Option) *ϡvm {
	for _, opt := range opts {
		opt(v)
	}
	return v
}

// addErr adds the error at the current parser position, without rule name
// information.
func (v *ϡvm) addErr(err error) {
	v.addErrAt(err, -1, v.parser.pt.position)
}

// addErrAt adds the error at the specified position, for the rule name at
// ruleNmIx.
func (v *ϡvm) addErrAt(err error, ruleNmIx int, pos position) {
	var buf bytes.Buffer
	if v.filename != "" {
		buf.WriteString(v.filename)
	}
	if buf.Len() > 0 {
		buf.WriteString(":")
	}
	buf.WriteString(fmt.Sprintf("%s", pos))

	ruleNm := v.pg.ruleNameAt(ruleNmIx)
	if ruleNm != "" {
		buf.WriteString(": ")
		buf.WriteString("rule " + ruleNm)
	}

	pe := &parserError{Inner: err, ϡprefix: buf.String()}
	v.errs.ϡadd(pe)
}

// dumpSnapshot writes a dump of the current VM state to w.
func (v *ϡvm) dumpSnapshot(w io.Writer) {
	var buf bytes.Buffer

	if v.filename != "" {
		buf.WriteString(v.filename + ":")
	}
	buf.WriteString(fmt.Sprintf("%s: %#U\n", v.parser.pt.position, v.parser.pt.rn))

	// write the next 5 instructions
	ix := v.pc - 1
	if ix > 0 {
		ix--
	}
	stdFmt := ". [%d]: %s"
	for i := 0; i < 5; i++ {
		stdFmt := stdFmt
		if ix == v.pc-1 {
			stdFmt = ">" + stdFmt[1:]
		}
		instr := v.pg.instrs[ix]
		switch instr.op {
		case ϡopCall:
			buf.WriteString(fmt.Sprintf(stdFmt+"\n", ix, v.pg.instrToString(instr)))
			ix = v.i.pop() // continue with instructions at this index
			v.i.push(ix)
			continue
		default:
			buf.WriteString(fmt.Sprintf(stdFmt+"\n", ix, v.pg.instrToString(instr)))
		}
		ix++
		if int(ix) >= len(v.pg.instrs) {
			break
		}
	}

	// // print the stacks
	// buf.WriteString("[ P: ")
	// for i := 0; i < 3; i++ {
	// 	if len(v.p) <= i {
	// 		break
	// 	}
	// 	if i > 0 {
	// 		buf.WriteString(", ")
	// 	}
	// 	val := v.p[len(v.p)-i-1]
	// 	buf.WriteString(fmt.Sprintf("\"%v\"", val))
	// }
	// buf.WriteString(" ]\n[ V: ")
	// for i := 0; i < 3; i++ {
	// 	if len(v.v) <= i {
	// 		break
	// 	}
	// 	if i > 0 {
	// 		buf.WriteString(", ")
	// 	}
	// 	val := v.v[len(v.v)-i-1]
	// 	buf.WriteString(fmt.Sprintf("%#v", val))
	// }
	// buf.WriteString(" ]\n[ I: ")
	// for i := 0; i < 3; i++ {
	// 	if len(v.i) <= i {
	// 		break
	// 	}
	// 	if i > 0 {
	// 		buf.WriteString(", ")
	// 	}
	// 	val := v.i[len(v.i)-i-1]
	// 	buf.WriteString(fmt.Sprintf("%d", val))
	// }
	// buf.WriteString(" ]\n[ L: ")
	// for i := 0; i < 3; i++ {
	// 	if len(v.l) <= i {
	// 		break
	// 	}
	// 	if i > 0 {
	// 		buf.WriteString(", ")
	// 	}
	// 	val := v.l[len(v.l)-i-1]
	// 	buf.WriteString(fmt.Sprintf("%v", val))
	// }
	// buf.WriteString(" ]\n")
	fmt.Fprintln(w, buf.String())
}

// run executes the provided program in this VM, and returns the result.
func (v *ϡvm) run(pg *ϡprogram) (interface{}, error) {
	v.pg = pg
	v.a = newAstack(128)
	v.i = newIstack(128)
	v.v = newVstack(128)
	v.l = newLstack(128)
	v.p = newPstack(128)
	ret := v.dispatch()

	// if the match failed, translate that to a nil result and make
	// sure it returns an error
	if ret == ϡmatchFailed {
		ret = nil
		if len(v.errs) == 0 {
			v.addErr(errNoMatch)
		}
	}

	return ret, v.errs.ϡerr()
}

// dispatch is the proper execution method of the VM, it loops over
// the instructions and executes each opcode.
func (v *ϡvm) dispatch() interface{} {
	var instrPath []uint16
	if v.debug {
		fmt.Fprintln(os.Stderr, v.pg)
		defer func() {
			var buf bytes.Buffer

			buf.WriteString("Execution path:\n")
			for _, ix := range instrPath {
				buf.WriteString(fmt.Sprintf("[%3d]: %s\n", ix, v.pg.instrToString(v.pg.instrs[ix])))
			}
			fmt.Fprintln(os.Stderr, buf.String())
		}()
	}

	if v.recover {
		defer func() {
			if e := recover(); e != nil {
				ruleIx := -1
				if v.pc > 0 {
					ruleIx = v.pg.instrs[v.pc-1].ruleNmIx
				}
				switch e := e.(type) {
				case error:
					v.addErrAt(e, ruleIx, v.parser.pt.position)
				default:
					v.addErrAt(fmt.Errorf("%v", e), ruleIx, v.parser.pt.position)
				}
			}
		}()
	}

	// move to first rune before starting the loop
	v.parser.read()
	for {
		// fetch and decode the instruction
		instr := v.pg.instrs[v.pc]
		instrPath = append(instrPath, v.pc)

		// increment program counter
		v.pc++

		switch instr.op {
		case ϡopCall:
			if v.debug {
				v.dumpSnapshot(os.Stderr)
			}
			ix := v.i.pop()
			v.i.push(v.pc)
			v.pc = ix

		case ϡopCallA:
			if v.debug {
				v.dumpSnapshot(os.Stderr)
			}
			v.v.pop()
			start := v.p.pop()
			v.cur.pos = start.position
			v.cur.text = v.parser.sliceFrom(start)
			if int(instr.args[0]) >= len(v.pg.as) {
				panic(fmt.Sprintf("invalid %s argument: %d", instr.op, instr.args[0]))
			}
			fn := v.pg.as[instr.args[0]]
			val, err := fn(v)
			if err != nil {
				v.addErrAt(err, int(instr.ruleNmIx), start.position)
			}
			v.v.push(val)

		case ϡopCallB:
			if v.debug {
				v.dumpSnapshot(os.Stderr)
			}
			v.cur.pos = v.parser.pt.position
			v.cur.text = nil
			if int(instr.args[0]) >= len(v.pg.bs) {
				panic(fmt.Sprintf("invalid %s argument: %d", instr.op, instr.args[0]))
			}
			fn := v.pg.bs[instr.args[0]]
			val, err := fn(v)
			if err != nil {
				v.addErrAt(err, int(instr.ruleNmIx), v.parser.pt.position)
			}
			if !val {
				v.v.push(ϡmatchFailed)
				break
			}
			v.v.push(nil)

		case ϡopCumulOrF:
			va, vb := v.v.pop(), v.v.pop()
			if va == ϡmatchFailed {
				v.v.push(ϡmatchFailed)
				break
			}
			switch vb := vb.(type) {
			case []interface{}:
				vb = append(vb, va)
				v.v.push(vb)
			case ϡsentinel:
				v.v.push([]interface{}{va})
			default:
				panic(fmt.Sprintf("invalid %s value type on the V stack: %T", instr.op, vb))
			}

		case ϡopExit:
			return v.v.pop()

		case ϡopNilIfF:
			if top := v.v.pop(); top == ϡmatchFailed {
				v.v.push(nil)
				break
			}
			v.v.push(ϡmatchFailed)

		case ϡopNilIfT:
			if top := v.v.pop(); top != ϡmatchFailed {
				v.v.push(nil)
				break
			}
			v.v.push(ϡmatchFailed)

		case ϡopJump:
			v.pc = instr.args[0]

		case ϡopJumpIfF:
			if top := v.v.peek(); top == ϡmatchFailed {
				v.pc = instr.args[0]
			}

		case ϡopJumpIfT:
			if top := v.v.peek(); top != ϡmatchFailed {
				v.pc = instr.args[0]
			}

		case ϡopMatch:
			start := v.parser.pt
			if int(instr.args[0]) >= len(v.pg.ms) {
				panic(fmt.Sprintf("invalid %s argument: %d", instr.op, instr.args[0]))
			}
			m := v.pg.ms[instr.args[0]]
			if ok := m.match(v.parser); ok {
				v.v.push(v.parser.sliceFrom(start))
				break
			}
			v.v.push(ϡmatchFailed)
			v.parser.pt = start

			if v.debug {
				v.dumpSnapshot(os.Stderr)
			}

		case ϡopPop:
			switch instr.args[0] {
			case ϡlstackID:
				v.l.pop()
			case ϡpstackID:
				v.p.pop()
			case ϡastackID:
				v.a.pop()
			case ϡvstackID:
				v.v.pop()
			default:
				panic(fmt.Sprintf("invalid %s argument: %d", instr.op, instr.args[0]))
			}

		case ϡopPopVJumpIfF:
			if top := v.v.peek(); top == ϡmatchFailed {
				v.v.pop()
				v.pc = instr.args[0]
			}

		case ϡopPush:
			switch instr.args[0] {
			case ϡpstackID:
				v.p.push(v.parser.pt)
			case ϡistackID:
				v.i.push(instr.args[1])
			case ϡvstackID:
				if int(instr.args[1]) >= len(ϡvSpecialValues) {
					panic(fmt.Sprintf("invalid %s V stack argument: %d", instr.op, instr.args[1]))
				}
				v.v.push(ϡvSpecialValues[instr.args[1]])
			case ϡastackID:
				v.a.push()
			case ϡlstackID:
				v.l.push(instr.args[1:])
			default:
				panic(fmt.Sprintf("invalid %s argument: %d", instr.op, instr.args[0]))
			}

		case ϡopRestore:
			pt := v.p.pop()
			v.parser.pt = pt

		case ϡopRestoreIfF:
			pt := v.p.pop()
			if top := v.v.peek(); top == ϡmatchFailed {
				v.parser.pt = pt
			}

		case ϡopReturn:
			ix := v.i.pop()
			v.pc = ix

		case ϡopStoreIfT:
			if top := v.v.peek(); top != ϡmatchFailed {
				// get the label name
				if int(instr.args[0]) >= len(v.pg.ss) {
					panic(fmt.Sprintf("invalid %s argument: %d", instr.op, instr.args[0]))
				}
				lbl := v.pg.ss[instr.args[0]]

				// store the value
				as := v.a.peek()
				as[lbl] = top
			}

		case ϡopTakeLOrJump:
			ix := v.l.take()
			if ix < 0 {
				v.pc = instr.args[0]
				break
			}
			v.i.push(uint16(ix))

		default:
			panic(fmt.Sprintf("unknown opcode %s", instr.op))
		}
	}
}
