{
package main

func main() {
	in := os.Stdin
	if len(os.Args) > 1 {
		f, err := os.Open(os.Args[1])
		if err != nil {
			log.Fatal(err)
		}
		defer f.Close()
		in = f
	}
	got, err := ParseReader("", in, Debug(true))
	fmt.Println(got, err)
}

}

start = #{ c.state["countCs"] = 0; return nil } ((x/y/z) ws*)* { return c.state["countCs"], nil }

x = "ab" c "d"
y = "a" bc "e"
z = "abcf" { c.state["countCs"] = c.state["countCs"].(int) + 5; return nil, nil}

c = "c" &{ c.state["countCs"] = c.state["countCs"].(int) + 3; return true, nil }
bc = "bc" !{ c.state["countCs"] = c.state["countCs"].(int) + 1; return false, nil}

ws = " " / "\n"
