// Code generated by pigeon (https://github.com/PuerkitoBio/pigeon)
// on 2015-05-09 12:03:26.004686221 -0400 EDT

// Command json parses JSON as defined by [1].
//
// BUGS: the escaped forward solidus (`\/`) is not currently handled.
//
// [1]: http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf
package main

import (
	"bytes"
	"errors"
	"fmt"
	"io"
	"io/ioutil"
	"log"
	"os"
	"strconv"
	"unicode"
	"unicode/utf8"
)

func main() {
	in := os.Stdin
	nm := "stdin"
	if len(os.Args) > 1 {
		f, err := os.Open(os.Args[1])
		if err != nil {
			log.Fatal(err)
		}
		defer f.Close()
		in = f
		nm = os.Args[1]
	}

	got, err := ParseReader(nm, in)
	if err != nil {
		log.Fatal(err)
	}
	fmt.Println(got)
}

func toIfaceSlice(v interface{}) []interface{} {
	if v == nil {
		return nil
	}
	return v.([]interface{})
}

func (c *current) onJSON1(vals interface{}) (interface{}, error) {
	valsSl := toIfaceSlice(vals)
	switch len(valsSl) {
	case 0:
		return nil, nil
	case 1:
		return valsSl[0], nil
	default:
		return valsSl, nil
	}
}

func (v *ϡvm) callOnJSON1() (interface{}, error) {
	stack := v.a.peek()
	return v.cur.onJSON1(stack["vals"])
}

func (c *current) onValue1(val interface{}) (interface{}, error) {
	return val, nil
}

func (v *ϡvm) callOnValue1() (interface{}, error) {
	stack := v.a.peek()
	return v.cur.onValue1(stack["val"])
}

func (c *current) onObject1(vals interface{}) (interface{}, error) {
	res := make(map[string]interface{})
	valsSl := toIfaceSlice(vals)
	if len(valsSl) == 0 {
		return res, nil
	}
	res[valsSl[0].(string)] = valsSl[4]
	restSl := toIfaceSlice(valsSl[5])
	for _, v := range restSl {
		vSl := toIfaceSlice(v)
		res[vSl[2].(string)] = vSl[6]
	}
	return res, nil
}

func (v *ϡvm) callOnObject1() (interface{}, error) {
	stack := v.a.peek()
	return v.cur.onObject1(stack["vals"])
}

func (c *current) onArray1(vals interface{}) (interface{}, error) {
	valsSl := toIfaceSlice(vals)
	if len(valsSl) == 0 {
		return []interface{}{}, nil
	}
	res := []interface{}{valsSl[0]}
	restSl := toIfaceSlice(valsSl[1])
	for _, v := range restSl {
		vSl := toIfaceSlice(v)
		res = append(res, vSl[2])
	}
	return res, nil
}

func (v *ϡvm) callOnArray1() (interface{}, error) {
	stack := v.a.peek()
	return v.cur.onArray1(stack["vals"])
}

func (c *current) onNumber1() (interface{}, error) {
	// JSON numbers have the same syntax as Go's, and are parseable using
	// strconv.
	return strconv.ParseFloat(string(c.text), 64)
}

func (v *ϡvm) callOnNumber1() (interface{}, error) {
	return v.cur.onNumber1()
}

func (c *current) onString1() (interface{}, error) {
	// TODO : the forward slash (solidus) is not a valid escape in Go, it will
	// fail if there's one in the string
	return strconv.Unquote(string(c.text))
}

func (v *ϡvm) callOnString1() (interface{}, error) {
	return v.cur.onString1()
}

func (c *current) onBool2() (interface{}, error) { return true, nil }

func (v *ϡvm) callOnBool2() (interface{}, error) {
	return v.cur.onBool2()
}

func (c *current) onBool4() (interface{}, error) { return false, nil }

func (v *ϡvm) callOnBool4() (interface{}, error) {
	return v.cur.onBool4()
}

func (c *current) onNull1() (interface{}, error) { return nil, nil }

func (v *ϡvm) callOnNull1() (interface{}, error) {
	return v.cur.onNull1()
}

var ϡtheProgram = &ϡprogram{
	instrs: []ϡinstr{
		{13, -1, []uint16{4, 45}}, {13, -1, []uint16{5}},
		{1, -1, nil}, {0, -1, nil},
		{13, 0, []uint16{4, 748}}, {13, 0, []uint16{5}},
		{1, 0, nil}, {11, 0, []uint16{5}},
		{16, 0, nil}, {13, 0, []uint16{4, 116}},
		{13, 0, []uint16{5}}, {1, 0, nil},
		{11, 0, []uint16{5}}, {16, 0, nil},
		{13, 0, []uint16{3, 1}}, {13, 0, []uint16{4, 9}},
		{13, 0, []uint16{5}}, {1, 0, nil},
		{11, 0, []uint16{5}}, {12, 0, []uint16{22}},
		{4, 0, nil}, {5, 0, []uint16{15}},
		{16, 0, nil}, {13, 0, []uint16{4, 14}},
		{13, 0, []uint16{5}}, {1, 0, nil},
		{11, 0, []uint16{5}}, {17, 0, []uint16{2}},
		{16, 0, nil}, {13, 0, []uint16{4, 761}},
		{13, 0, []uint16{5}}, {1, 0, nil},
		{11, 0, []uint16{5}}, {16, 0, nil},
		{13, 0, []uint16{1}}, {13, 0, []uint16{3, 1}},
		{13, 0, []uint16{2, 4, 23, 29}}, {18, 0, []uint16{42}},
		{1, 0, nil}, {4, 0, nil},
		{6, 0, []uint16{42}}, {5, 0, []uint16{37}},
		{11, 0, []uint16{2}}, {15, 0, nil},
		{16, 0, nil}, {13, 0, []uint16{1}},
		{13, 0, []uint16{4, 34}}, {1, 0, nil},
		{6, 0, []uint16{51}}, {2, 0, []uint16{0}},
		{16, 0, nil}, {11, 0, []uint16{1}},
		{16, 0, nil}, {13, 3, []uint16{4, 250}},
		{13, 3, []uint16{5}}, {1, 3, nil},
		{11, 3, []uint16{5}}, {16, 3, nil},
		{13, 3, []uint16{4, 346}}, {13, 3, []uint16{5}},
		{1, 3, nil}, {11, 3, []uint16{5}},
		{16, 3, nil}, {13, 3, []uint16{4, 432}},
		{13, 3, []uint16{5}}, {1, 3, nil},
		{11, 3, []uint16{5}}, {16, 3, nil},
		{13, 3, []uint16{4, 613}}, {13, 3, []uint16{5}},
		{1, 3, nil}, {11, 3, []uint16{5}},
		{16, 3, nil}, {13, 3, []uint16{4, 721}},
		{13, 3, []uint16{5}}, {1, 3, nil},
		{11, 3, []uint16{5}}, {16, 3, nil},
		{13, 3, []uint16{4, 736}}, {13, 3, []uint16{5}},
		{1, 3, nil}, {11, 3, []uint16{5}},
		{16, 3, nil}, {13, 3, []uint16{2, 53, 58, 63, 68, 73, 78}},
		{18, 3, []uint16{91}}, {13, 3, []uint16{5}},
		{1, 3, nil}, {11, 3, []uint16{5}},
		{7, 3, []uint16{92}}, {11, 3, []uint16{3}},
		{5, 3, []uint16{84}}, {13, 3, []uint16{3, 1}},
		{11, 3, []uint16{2}}, {16, 3, nil},
		{13, 3, []uint16{4, 83}}, {13, 3, []uint16{5}},
		{1, 3, nil}, {11, 3, []uint16{5}},
		{17, 3, []uint16{5}}, {16, 3, nil},
		{13, 3, []uint16{4, 748}}, {13, 3, []uint16{5}},
		{1, 3, nil}, {11, 3, []uint16{5}},
		{16, 3, nil}, {13, 3, []uint16{1}},
		{13, 3, []uint16{3, 1}}, {13, 3, []uint16{2, 94, 100}},
		{18, 3, []uint16{113}}, {1, 3, nil},
		{4, 3, nil}, {6, 3, []uint16{113}},
		{5, 3, []uint16{108}}, {11, 3, []uint16{2}},
		{15, 3, nil}, {16, 3, nil},
		{13, 3, []uint16{1}}, {13, 3, []uint16{4, 105}},
		{1, 3, nil}, {6, 3, []uint16{122}},
		{2, 3, []uint16{1}}, {16, 3, nil},
		{11, 3, []uint16{1}}, {16, 3, nil},
		{13, 6, []uint16{1}}, {8, 6, []uint16{0}},
		{15, 6, nil}, {16, 6, nil},
		{13, 6, []uint16{4, 748}}, {13, 6, []uint16{5}},
		{1, 6, nil}, {11, 6, []uint16{5}},
		{16, 6, nil}, {13, 6, []uint16{4, 613}},
		{13, 6, []uint16{5}}, {1, 6, nil},
		{11, 6, []uint16{5}}, {16, 6, nil},
		{13, 6, []uint16{4, 748}}, {13, 6, []uint16{5}},
		{1, 6, nil}, {11, 6, []uint16{5}},
		{16, 6, nil}, {13, 6, []uint16{1}},
		{8, 6, []uint16{1}}, {15, 6, nil},
		{16, 6, nil}, {13, 6, []uint16{4, 748}},
		{13, 6, []uint16{5}}, {1, 6, nil},
		{11, 6, []uint16{5}}, {16, 6, nil},
		{13, 6, []uint16{4, 116}}, {13, 6, []uint16{5}},
		{1, 6, nil}, {11, 6, []uint16{5}},
		{16, 6, nil}, {13, 6, []uint16{1}},
		{8, 6, []uint16{2}}, {15, 6, nil},
		{16, 6, nil}, {13, 6, []uint16{4, 748}},
		{13, 6, []uint16{5}}, {1, 6, nil},
		{11, 6, []uint16{5}}, {16, 6, nil},
		{13, 6, []uint16{4, 613}}, {13, 6, []uint16{5}},
		{1, 6, nil}, {11, 6, []uint16{5}},
		{16, 6, nil}, {13, 6, []uint16{4, 748}},
		{13, 6, []uint16{5}}, {1, 6, nil},
		{11, 6, []uint16{5}}, {16, 6, nil},
		{13, 6, []uint16{1}}, {8, 6, []uint16{1}},
		{15, 6, nil}, {16, 6, nil},
		{13, 6, []uint16{4, 748}}, {13, 6, []uint16{5}},
		{1, 6, nil}, {11, 6, []uint16{5}},
		{16, 6, nil}, {13, 6, []uint16{4, 116}},
		{13, 6, []uint16{5}}, {1, 6, nil},
		{11, 6, []uint16{5}}, {16, 6, nil},
		{13, 6, []uint16{1}}, {13, 6, []uint16{3, 1}},
		{13, 6, []uint16{2, 157, 161, 166, 171, 176, 180, 185}}, {18, 6, []uint16{198}},
		{1, 6, nil}, {4, 6, nil},
		{6, 6, []uint16{198}}, {5, 6, []uint16{193}},
		{11, 6, []uint16{2}}, {15, 6, nil},
		{16, 6, nil}, {13, 6, []uint16{3, 2}},
		{13, 6, []uint16{4, 190}}, {13, 6, []uint16{5}},
		{1, 6, nil}, {11, 6, []uint16{5}},
		{12, 6, []uint16{209}}, {4, 6, nil},
		{5, 6, []uint16{202}}, {16, 6, nil},
		{13, 6, []uint16{1}}, {13, 6, []uint16{3, 1}},
		{13, 6, []uint16{2, 133, 138, 143, 147, 152, 201}}, {18, 6, []uint16{218}},
		{1, 6, nil}, {4, 6, nil},
		{6, 6, []uint16{218}}, {5, 6, []uint16{213}},
		{11, 6, []uint16{2}}, {15, 6, nil},
		{16, 6, nil}, {13, 6, []uint16{4, 210}},
		{13, 6, []uint16{5}}, {1, 6, nil},
		{11, 6, []uint16{5}}, {12, 6, []uint16{227}},
		{16, 6, nil}, {13, 6, []uint16{3, 0}},
		{16, 6, nil}, {13, 6, []uint16{4, 221}},
		{13, 6, []uint16{5}}, {1, 6, nil},
		{11, 6, []uint16{5}}, {17, 6, []uint16{2}},
		{16, 6, nil}, {13, 6, []uint16{1}},
		{8, 6, []uint16{3}}, {15, 6, nil},
		{16, 6, nil}, {13, 6, []uint16{1}},
		{13, 6, []uint16{3, 1}}, {13, 6, []uint16{2, 124, 128, 229, 235}},
		{18, 6, []uint16{247}}, {1, 6, nil},
		{4, 6, nil}, {6, 6, []uint16{247}},
		{5, 6, []uint16{242}}, {11, 6, []uint16{2}},
		{15, 6, nil}, {16, 6, nil},
		{13, 6, []uint16{1}}, {13, 6, []uint16{4, 239}},
		{1, 6, nil}, {6, 6, []uint16{256}},
		{2, 6, []uint16{2}}, {16, 6, nil},
		{11, 6, []uint16{1}}, {16, 6, nil},
		{13, 7, []uint16{1}}, {8, 7, []uint16{4}},
		{15, 7, nil}, {16, 7, nil},
		{13, 7, []uint16{4, 748}}, {13, 7, []uint16{5}},
		{1, 7, nil}, {11, 7, []uint16{5}},
		{16, 7, nil}, {13, 7, []uint16{4, 116}},
		{13, 7, []uint16{5}}, {1, 7, nil},
		{11, 7, []uint16{5}}, {16, 7, nil},
		{13, 7, []uint16{1}}, {8, 7, []uint16{2}},
		{15, 7, nil}, {16, 7, nil},
		{13, 7, []uint16{4, 748}}, {13, 7, []uint16{5}},
		{1, 7, nil}, {11, 7, []uint16{5}},
		{16, 7, nil}, {13, 7, []uint16{4, 116}},
		{13, 7, []uint16{5}}, {1, 7, nil},
		{11, 7, []uint16{5}}, {16, 7, nil},
		{13, 7, []uint16{1}}, {13, 7, []uint16{3, 1}},
		{13, 7, []uint16{2, 272, 276, 281}}, {18, 7, []uint16{294}},
		{1, 7, nil}, {4, 7, nil},
		{6, 7, []uint16{294}}, {5, 7, []uint16{289}},
		{11, 7, []uint16{2}}, {15, 7, nil},
		{16, 7, nil}, {13, 7, []uint16{3, 2}},
		{13, 7, []uint16{4, 286}}, {13, 7, []uint16{5}},
		{1, 7, nil}, {11, 7, []uint16{5}},
		{12, 7, []uint16{305}}, {4, 7, nil},
		{5, 7, []uint16{298}}, {16, 7, nil},
		{13, 7, []uint16{1}}, {13, 7, []uint16{3, 1}},
		{13, 7, []uint16{2, 267, 297}}, {18, 7, []uint16{314}},
		{1, 7, nil}, {4, 7, nil},
		{6, 7, []uint16{314}}, {5, 7, []uint16{309}},
		{11, 7, []uint16{2}}, {15, 7, nil},
		{16, 7, nil}, {13, 7, []uint16{4, 306}},
		{13, 7, []uint16{5}}, {1, 7, nil},
		{11, 7, []uint16{5}}, {12, 7, []uint16{323}},
		{16, 7, nil}, {13, 7, []uint16{3, 0}},
		{16, 7, nil}, {13, 7, []uint16{4, 317}},
		{13, 7, []uint16{5}}, {1, 7, nil},
		{11, 7, []uint16{5}}, {17, 7, []uint16{2}},
		{16, 7, nil}, {13, 7, []uint16{1}},
		{8, 7, []uint16{5}}, {15, 7, nil},
		{16, 7, nil}, {13, 7, []uint16{1}},
		{13, 7, []uint16{3, 1}}, {13, 7, []uint16{2, 258, 262, 325, 331}},
		{18, 7, []uint16{343}}, {1, 7, nil},
		{4, 7, nil}, {6, 7, []uint16{343}},
		{5, 7, []uint16{338}}, {11, 7, []uint16{2}},
		{15, 7, nil}, {16, 7, nil},
		{13, 7, []uint16{1}}, {13, 7, []uint16{4, 335}},
		{1, 7, nil}, {6, 7, []uint16{352}},
		{2, 7, []uint16{3}}, {16, 7, nil},
		{11, 7, []uint16{1}}, {16, 7, nil},
		{13, 8, []uint16{1}}, {8, 8, []uint16{6}},
		{15, 8, nil}, {16, 8, nil},
		{13, 8, []uint16{4, 354}}, {13, 8, []uint16{5}},
		{1, 8, nil}, {11, 8, []uint16{5}},
		{12, 8, []uint16{364}}, {16, 8, nil},
		{13, 8, []uint16{3, 0}}, {16, 8, nil},
		{13, 8, []uint16{4, 474}}, {13, 8, []uint16{5}},
		{1, 8, nil}, {11, 8, []uint16{5}},
		{16, 8, nil}, {13, 8, []uint16{1}},
		{8, 8, []uint16{7}}, {15, 8, nil},
		{16, 8, nil}, {13, 8, []uint16{4, 685}},
		{13, 8, []uint16{5}}, {1, 8, nil},
		{11, 8, []uint16{5}}, {16, 8, nil},
		{13, 8, []uint16{3, 1}}, {13, 8, []uint16{4, 375}},
		{13, 8, []uint16{5}}, {1, 8, nil},
		{11, 8, []uint16{5}}, {12, 8, []uint16{388}},
		{4, 8, nil}, {5, 8, []uint16{381}},
		{16, 8, nil}, {13, 8, []uint16{1}},
		{13, 8, []uint16{3, 1}}, {13, 8, []uint16{2, 371, 380}},
		{18, 8, []uint16{397}}, {1, 8, nil},
		{4, 8, nil}, {6, 8, []uint16{397}},
		{5, 8, []uint16{392}}, {11, 8, []uint16{2}},
		{15, 8, nil}, {16, 8, nil},
		{13, 8, []uint16{4, 389}}, {13, 8, []uint16{5}},
		{1, 8, nil}, {11, 8, []uint16{5}},
		{12, 8, []uint16{406}}, {16, 8, nil},
		{13, 8, []uint16{3, 0}}, {16, 8, nil},
		{13, 8, []uint16{4, 515}}, {13, 8, []uint16{5}},
		{1, 8, nil}, {11, 8, []uint16{5}},
		{16, 8, nil}, {13, 8, []uint16{4, 408}},
		{13, 8, []uint16{5}}, {1, 8, nil},
		{11, 8, []uint16{5}}, {12, 8, []uint16{419}},
		{16, 8, nil}, {13, 8, []uint16{3, 0}},
		{16, 8, nil}, {13, 8, []uint16{1}},
		{13, 8, []uint16{3, 1}}, {13, 8, []uint16{2, 358, 366, 400, 413}},
		{18, 8, []uint16{429}}, {1, 8, nil},
		{4, 8, nil}, {6, 8, []uint16{429}},
		{5, 8, []uint16{424}}, {11, 8, []uint16{2}},
		{15, 8, nil}, {16, 8, nil},
		{13, 8, []uint16{1}}, {13, 8, []uint16{4, 421}},
		{1, 8, nil}, {6, 8, []uint16{438}},
		{2, 8, []uint16{4}}, {16, 8, nil},
		{11, 8, []uint16{1}}, {16, 8, nil},
		{13, 12, []uint16{1}}, {8, 12, []uint16{8}},
		{15, 12, nil}, {16, 12, nil},
		{13, 12, []uint16{4, 689}}, {13, 12, []uint16{5}},
		{1, 12, nil}, {11, 12, []uint16{5}},
		{16, 12, nil}, {13, 12, []uint16{4, 685}},
		{13, 12, []uint16{5}}, {1, 12, nil},
		{11, 12, []uint16{5}}, {16, 12, nil},
		{13, 12, []uint16{3, 2}}, {13, 12, []uint16{4, 449}},
		{13, 12, []uint16{5}}, {1, 12, nil},
		{11, 12, []uint16{5}}, {12, 12, []uint16{462}},
		{4, 12, nil}, {5, 12, []uint16{455}},
		{16, 12, nil}, {13, 12, []uint16{1}},
		{13, 12, []uint16{3, 1}}, {13, 12, []uint16{2, 444, 454}},
		{18, 12, []uint16{471}}, {1, 12, nil},
		{4, 12, nil}, {6, 12, []uint16{471}},
		{5, 12, []uint16{466}}, {11, 12, []uint16{2}},
		{15, 12, nil}, {16, 12, nil},
		{13, 12, []uint16{2, 440, 463}}, {18, 12, []uint16{482}},
		{13, 12, []uint16{5}}, {1, 12, nil},
		{11, 12, []uint16{5}}, {7, 12, []uint16{483}},
		{11, 12, []uint16{3}}, {5, 12, []uint16{475}},
		{13, 12, []uint16{3, 1}}, {11, 12, []uint16{2}},
		{16, 12, nil}, {13, 14, []uint16{1}},
		{8, 14, []uint16{9}}, {15, 14, nil},
		{16, 14, nil}, {13, 14, []uint16{1}},
		{8, 14, []uint16{10}}, {15, 14, nil},
		{16, 14, nil}, {13, 14, []uint16{4, 489}},
		{13, 14, []uint16{5}}, {1, 14, nil},
		{11, 14, []uint16{5}}, {12, 14, []uint16{499}},
		{16, 14, nil}, {13, 14, []uint16{3, 0}},
		{16, 14, nil}, {13, 14, []uint16{4, 685}},
		{13, 14, []uint16{5}}, {1, 14, nil},
		{11, 14, []uint16{5}}, {16, 14, nil},
		{13, 14, []uint16{3, 1}}, {13, 14, []uint16{4, 501}},
		{13, 14, []uint16{5}}, {1, 14, nil},
		{11, 14, []uint16{5}}, {12, 14, []uint16{514}},
		{4, 14, nil}, {5, 14, []uint16{507}},
		{16, 14, nil}, {13, 14, []uint16{1}},
		{13, 14, []uint16{3, 1}}, {13, 14, []uint16{2, 485, 493, 506}},
		{18, 14, []uint16{523}}, {1, 14, nil},
		{4, 14, nil}, {6, 14, []uint16{523}},
		{5, 14, []uint16{518}}, {11, 14, []uint16{2}},
		{15, 14, nil}, {16, 14, nil},
		{13, 9, []uint16{1}}, {8, 9, []uint16{11}},
		{15, 9, nil}, {16, 9, nil},
		{13, 9, []uint16{4, 621}}, {13, 9, []uint16{5}},
		{1, 9, nil}, {11, 9, []uint16{5}},
		{16, 9, nil}, {13, 9, []uint16{1}},
		{13, 9, []uint16{4, 530}}, {13, 9, []uint16{5}},
		{1, 9, nil}, {11, 9, []uint16{5}},
		{9, 9, nil}, {14, 9, nil},
		{16, 9, nil}, {13, 9, []uint16{1}},
		{8, 9, []uint16{12}}, {15, 9, nil},
		{16, 9, nil}, {13, 9, []uint16{1}},
		{13, 9, []uint16{3, 1}}, {13, 9, []uint16{2, 535, 543}},
		{18, 9, []uint16{555}}, {1, 9, nil},
		{4, 9, nil}, {6, 9, []uint16{555}},
		{5, 9, []uint16{550}}, {11, 9, []uint16{2}},
		{15, 9, nil}, {16, 9, nil},
		{13, 9, []uint16{1}}, {8, 9, []uint16{13}},
		{15, 9, nil}, {16, 9, nil},
		{13, 9, []uint16{4, 635}}, {13, 9, []uint16{5}},
		{1, 9, nil}, {11, 9, []uint16{5}},
		{16, 9, nil}, {13, 9, []uint16{1}},
		{13, 9, []uint16{3, 1}}, {13, 9, []uint16{2, 558, 562}},
		{18, 9, []uint16{575}}, {1, 9, nil},
		{4, 9, nil}, {6, 9, []uint16{575}},
		{5, 9, []uint16{570}}, {11, 9, []uint16{2}},
		{15, 9, nil}, {16, 9, nil},
		{13, 9, []uint16{2, 547, 567}}, {18, 9, []uint16{586}},
		{13, 9, []uint16{5}}, {1, 9, nil},
		{11, 9, []uint16{5}}, {7, 9, []uint16{587}},
		{11, 9, []uint16{3}}, {5, 9, []uint16{579}},
		{13, 9, []uint16{3, 1}}, {11, 9, []uint16{2}},
		{16, 9, nil}, {13, 9, []uint16{3, 2}},
		{13, 9, []uint16{4, 578}}, {13, 9, []uint16{5}},
		{1, 9, nil}, {11, 9, []uint16{5}},
		{12, 9, []uint16{597}}, {4, 9, nil},
		{5, 9, []uint16{590}}, {16, 9, nil},
		{13, 9, []uint16{1}}, {8, 9, []uint16{11}},
		{15, 9, nil}, {16, 9, nil},
		{13, 9, []uint16{1}}, {13, 9, []uint16{3, 1}},
		{13, 9, []uint16{2, 526, 589, 598}}, {18, 9, []uint16{610}},
		{1, 9, nil}, {4, 9, nil},
		{6, 9, []uint16{610}}, {5, 9, []uint16{605}},
		{11, 9, []uint16{2}}, {15, 9, nil},
		{16, 9, nil}, {13, 9, []uint16{1}},
		{13, 9, []uint16{4, 602}}, {1, 9, nil},
		{6, 9, []uint16{619}}, {2, 9, []uint16{5}},
		{16, 9, nil}, {11, 9, []uint16{1}},
		{16, 9, nil}, {13, 16, []uint16{1}},
		{8, 16, []uint16{14}}, {15, 16, nil},
		{16, 16, nil}, {13, 17, []uint16{4, 646}},
		{13, 17, []uint16{5}}, {1, 17, nil},
		{11, 17, []uint16{5}}, {16, 17, nil},
		{13, 17, []uint16{4, 674}}, {13, 17, []uint16{5}},
		{1, 17, nil}, {11, 17, []uint16{5}},
		{16, 17, nil}, {13, 17, []uint16{2, 625, 630}},
		{18, 17, []uint16{643}}, {13, 17, []uint16{5}},
		{1, 17, nil}, {11, 17, []uint16{5}},
		{7, 17, []uint16{644}}, {11, 17, []uint16{3}},
		{5, 17, []uint16{636}}, {13, 17, []uint16{3, 1}},
		{11, 17, []uint16{2}}, {16, 17, nil},
		{13, 18, []uint16{1}}, {8, 18, []uint16{15}},
		{15, 18, nil}, {16, 18, nil},
		{13, 19, []uint16{1}}, {8, 19, []uint16{16}},
		{15, 19, nil}, {16, 19, nil},
		{13, 19, []uint16{4, 693}}, {13, 19, []uint16{5}},
		{1, 19, nil}, {11, 19, []uint16{5}},
		{16, 19, nil}, {13, 19, []uint16{4, 693}},
		{13, 19, []uint16{5}}, {1, 19, nil},
		{11, 19, []uint16{5}}, {16, 19, nil},
		{13, 19, []uint16{4, 693}}, {13, 19, []uint16{5}},
		{1, 19, nil}, {11, 19, []uint16{5}},
		{16, 19, nil}, {13, 19, []uint16{4, 693}},
		{13, 19, []uint16{5}}, {1, 19, nil},
		{11, 19, []uint16{5}}, {16, 19, nil},
		{13, 19, []uint16{1}}, {13, 19, []uint16{3, 1}},
		{13, 19, []uint16{2, 650, 654, 659, 664, 669}}, {18, 19, []uint16{682}},
		{1, 19, nil}, {4, 19, nil},
		{6, 19, []uint16{682}}, {5, 19, []uint16{677}},
		{11, 19, []uint16{2}}, {15, 19, nil},
		{16, 19, nil}, {13, 13, []uint16{1}},
		{8, 13, []uint16{17}}, {15, 13, nil},
		{16, 13, nil}, {13, 15, []uint16{1}},
		{8, 15, []uint16{18}}, {15, 15, nil},
		{16, 15, nil}, {13, 20, []uint16{1}},
		{8, 20, []uint16{19}}, {15, 20, nil},
		{16, 20, nil}, {13, 10, []uint16{1}},
		{8, 10, []uint16{20}}, {15, 10, nil},
		{16, 10, nil}, {13, 10, []uint16{1}},
		{13, 10, []uint16{4, 697}}, {1, 10, nil},
		{6, 10, []uint16{707}}, {2, 10, []uint16{6}},
		{16, 10, nil}, {11, 10, []uint16{1}},
		{16, 10, nil}, {13, 10, []uint16{1}},
		{8, 10, []uint16{21}}, {15, 10, nil},
		{16, 10, nil}, {13, 10, []uint16{1}},
		{13, 10, []uint16{4, 709}}, {1, 10, nil},
		{6, 10, []uint16{719}}, {2, 10, []uint16{7}},
		{16, 10, nil}, {11, 10, []uint16{1}},
		{16, 10, nil}, {13, 10, []uint16{2, 701, 713}},
		{18, 10, []uint16{729}}, {13, 10, []uint16{5}},
		{1, 10, nil}, {11, 10, []uint16{5}},
		{7, 10, []uint16{730}}, {11, 10, []uint16{3}},
		{5, 10, []uint16{722}}, {13, 10, []uint16{3, 1}},
		{11, 10, []uint16{2}}, {16, 10, nil},
		{13, 11, []uint16{1}}, {8, 11, []uint16{22}},
		{15, 11, nil}, {16, 11, nil},
		{13, 11, []uint16{1}}, {13, 11, []uint16{4, 732}},
		{1, 11, nil}, {6, 11, []uint16{742}},
		{2, 11, []uint16{8}}, {16, 11, nil},
		{11, 11, []uint16{1}}, {16, 11, nil},
		{13, 21, []uint16{1}}, {8, 21, []uint16{23}},
		{15, 21, nil}, {16, 21, nil},
		{13, 21, []uint16{3, 2}}, {13, 21, []uint16{4, 744}},
		{13, 21, []uint16{5}}, {1, 21, nil},
		{11, 21, []uint16{5}}, {12, 21, []uint16{756}},
		{4, 21, nil}, {5, 21, []uint16{749}},
		{16, 21, nil}, {13, 4, []uint16{1}},
		{8, 4, []uint16{12}}, {15, 4, nil},
		{16, 4, nil}, {13, 4, []uint16{1}},
		{13, 4, []uint16{4, 757}}, {13, 4, []uint16{5}},
		{1, 4, nil}, {11, 4, []uint16{5}},
		{9, 4, nil}, {14, 4, nil},
		{16, 4, nil},
	},
	ss: []string{
		"JSON", "_", "vals",
		"Value", "EOF", "val",
		"Object", "Array", "Number",
		"String", "Bool", "Null",
		"Integer", "DecimalDigit", "Exponent",
		"NonZeroDecimalDigit", "EscapedChar", "EscapeSequence",
		"SingleCharEscape", "UnicodeEscape", "HexDigit",
		"\"whitespace\"",
	},
	ms: []ϡmatcher{
		ϡstringMatcher{
			ignoreCase: false,
			value:      "{",
		},
		ϡstringMatcher{
			ignoreCase: false,
			value:      ":",
		},
		ϡstringMatcher{
			ignoreCase: false,
			value:      ",",
		},
		ϡstringMatcher{
			ignoreCase: false,
			value:      "}",
		},
		ϡstringMatcher{
			ignoreCase: false,
			value:      "[",
		},
		ϡstringMatcher{
			ignoreCase: false,
			value:      "]",
		},
		ϡstringMatcher{
			ignoreCase: false,
			value:      "-",
		},
		ϡstringMatcher{
			ignoreCase: false,
			value:      ".",
		},
		ϡstringMatcher{
			ignoreCase: false,
			value:      "0",
		},
		ϡstringMatcher{
			ignoreCase: true,
			value:      "e",
		},
		ϡcharClassMatcher{
			raw:        "[+-]",
			ignoreCase: false,
			inverted:   false,
			chars:      []rune{'+', '-'},
			ranges:     []rune{},
			classes:    []*unicode.RangeTable{},
		},
		ϡstringMatcher{
			ignoreCase: false,
			value:      "\"",
		},
		ϡanyMatcher{},
		ϡstringMatcher{
			ignoreCase: false,
			value:      "\\",
		},
		ϡcharClassMatcher{
			raw:        "[\\x00-\\x1f\"\\\\]",
			ignoreCase: false,
			inverted:   false,
			chars:      []rune{'"', '\\'},
			ranges:     []rune{'\x00', '\x1f'},
			classes:    []*unicode.RangeTable{},
		},
		ϡcharClassMatcher{
			raw:        "[\"\\\\/bfnrt]",
			ignoreCase: false,
			inverted:   false,
			chars:      []rune{'"', '\\', '/', 'b', 'f', 'n', 'r', 't'},
			ranges:     []rune{},
			classes:    []*unicode.RangeTable{},
		},
		ϡstringMatcher{
			ignoreCase: false,
			value:      "u",
		},
		ϡcharClassMatcher{
			raw:        "[0-9]",
			ignoreCase: false,
			inverted:   false,
			chars:      []rune{},
			ranges:     []rune{'0', '9'},
			classes:    []*unicode.RangeTable{},
		},
		ϡcharClassMatcher{
			raw:        "[1-9]",
			ignoreCase: false,
			inverted:   false,
			chars:      []rune{},
			ranges:     []rune{'1', '9'},
			classes:    []*unicode.RangeTable{},
		},
		ϡcharClassMatcher{
			raw:        "[0-9a-f]i",
			ignoreCase: true,
			inverted:   false,
			chars:      []rune{},
			ranges:     []rune{'0', '9', 'a', 'f'},
			classes:    []*unicode.RangeTable{},
		},
		ϡstringMatcher{
			ignoreCase: false,
			value:      "true",
		},
		ϡstringMatcher{
			ignoreCase: false,
			value:      "false",
		},
		ϡstringMatcher{
			ignoreCase: false,
			value:      "null",
		},
		ϡcharClassMatcher{
			raw:        "[ \\t\\r\\n]",
			ignoreCase: false,
			inverted:   false,
			chars:      []rune{' ', '\t', '\r', '\n'},
			ranges:     []rune{},
			classes:    []*unicode.RangeTable{},
		},
	},
	as: []func(*ϡvm) (interface{}, error){
		(*ϡvm).callOnJSON1,
		(*ϡvm).callOnValue1,
		(*ϡvm).callOnObject1,
		(*ϡvm).callOnArray1,
		(*ϡvm).callOnNumber1,
		(*ϡvm).callOnString1,
		(*ϡvm).callOnBool2,
		(*ϡvm).callOnBool4,
		(*ϡvm).callOnNull1,
	},
	bs: []func(*ϡvm) (bool, error){},
}

//+pigeon: err.go

var (
	// errInvalidEncoding is returned when the source is not properly
	// utf8-encoded.
	errInvalidEncoding = errors.New("invalid encoding")

	// errNoMatch is returned if no match could be found and no other
	// error has been raised.
	errNoMatch = errors.New("no match found")
)

// errList cumulates the errors found by the parser. It is part
// of the supported API.
type errList []error

// ϡadd adds err to the list of errors.
func (e *errList) ϡadd(err error) {
	if err != nil {
		*e = append(*e, err)
	}
}

// ϡerr returns the error list as an error, or nil if the list is empty.
func (e errList) ϡerr() error {
	if len(e) == 0 {
		return nil
	}
	e.ϡdedupe()
	return e
}

// ϡdedupe removes duplicate error messages from the list.
func (e *errList) ϡdedupe() {
	var cleaned []error
	set := make(map[string]bool)
	for _, err := range *e {
		if msg := err.Error(); !set[msg] {
			set[msg] = true
			cleaned = append(cleaned, err)
		}
	}
	*e = cleaned
}

// Error returns the error message for the errList. It implements the
// error interface.
func (e errList) Error() string {
	var buf bytes.Buffer

	for i, err := range e {
		if i > 0 {
			buf.WriteRune('\n')
		}
		buf.WriteString(err.Error())
	}
	return buf.String()
}

// parserError wraps an error with a prefix indicating the rule in which
// the error occurred. The original error is stored in the Inner field.
// It is part of the supported API.
type parserError struct {
	Inner   error
	ϡpos    position
	ϡprefix string
}

// Error returns the prefixed error message. It implements the error
// interface.
func (p *parserError) Error() string {
	return p.ϡprefix + ": " + p.Inner.Error()
}

//+pigeon: matchers.go

// ϡpeekReader is the interface that defines the peek and read
// methods.
type ϡpeekReader interface {
	peek() rune
	read()
}

// ϡmatcher is the interface that defines the match method.
type ϡmatcher interface {
	match(ϡpeekReader) bool
	toDisplayMsg() string
}

// ϡanyMatcher is a matcher that matches any character but the
// EOF.
type ϡanyMatcher struct{}

// match tries to match a character in the peekReader.
func (a ϡanyMatcher) match(pr ϡpeekReader) bool {
	rn := pr.peek()
	pr.read()
	return rn != utf8.RuneError
}

func (a ϡanyMatcher) toDisplayMsg() string {
	return "<any>"
}

func (a ϡanyMatcher) String() string {
	return "."
}

// ϡstringMatcher is a matcher that matches a string.
type ϡstringMatcher struct {
	ignoreCase bool
	value      string // value must be lowercase if ignoreCase is true
}

// match tries to match the string in the peekReader.
func (s ϡstringMatcher) match(pr ϡpeekReader) bool {
	for _, want := range s.value {
		rn := pr.peek()
		pr.read()
		if s.ignoreCase {
			rn = unicode.ToLower(rn)
		}
		if rn != want {
			return false
		}
	}
	return true
}

func (s ϡstringMatcher) toDisplayMsg() string {
	return s.String()
}

func (s ϡstringMatcher) String() string {
	v := strconv.Quote(s.value)
	if s.ignoreCase {
		v += "i"
	}
	return v
}

// ϡcharClassMatcher is a matcher that matches classes of characters.
type ϡcharClassMatcher struct {
	raw     string
	chars   []rune // runes must be lowercase if ignoreCase is true
	ranges  []rune // same for ranges
	classes []*unicode.RangeTable

	ignoreCase bool
	inverted   bool
}

func (c ϡcharClassMatcher) toDisplayMsg() string {
	return c.raw
}

func (c ϡcharClassMatcher) String() string {
	return c.raw
}

// match tries to match classes of characters in the peekReader.
func (c ϡcharClassMatcher) match(pr ϡpeekReader) bool {
	rn := pr.peek()
	pr.read()

	if c.ignoreCase {
		rn = unicode.ToLower(rn)
	}

	// try to match in the list of available chars
	for _, ch := range c.chars {
		if rn == ch {
			return !c.inverted
		}
	}

	// try to match in the list of ranges
	for i := 0; i < len(c.ranges); i += 2 {
		if rn >= c.ranges[i] && rn <= c.ranges[i+1] {
			return !c.inverted
		}
	}

	// try to match in the list of Unicode classes
	for _, cl := range c.classes {
		if unicode.Is(cl, rn) {
			return !c.inverted
		}
	}

	return c.inverted
}

// ϡrangeTable returns the corresponding unicode range table from the
// provided class name.
func ϡrangeTable(class string) *unicode.RangeTable {
	if rt, ok := unicode.Categories[class]; ok {
		return rt
	}
	if rt, ok := unicode.Properties[class]; ok {
		return rt
	}
	if rt, ok := unicode.Scripts[class]; ok {
		return rt
	}

	// cannot happen
	panic(fmt.Sprintf("invalid Unicode class: %s", class))
}

//+pigeon: ops.go

// ϡop represents an opcode.
type ϡop byte

// list of opcodes in the pigeon VM.
const (
	ϡopExit ϡop = iota
	ϡopCall
	ϡopCallA
	ϡopCallB
	ϡopCumulOrF
	ϡopJump
	ϡopJumpIfF
	ϡopJumpIfT
	ϡopMatch
	ϡopNilIfF
	ϡopNilIfT
	ϡopPop
	ϡopPopVJumpIfF
	ϡopPush
	ϡopRestore
	ϡopRestoreIfF
	ϡopReturn
	ϡopStoreIfT
	ϡopTakeLOrJump
	ϡopmax // must always be after the last valid opcode

	// ϡopPlaceholder is an (invalid) opcode used by the Generator
	// to insert opcodes that need the index of the starting instruction
	// of a rule that hasn't been generated yet.
	//
	// It must be placed after ϡopmax (because it is invalid in the
	// final program) and it has one argument, the index in the strings
	// array of the identifier of the rule.
	ϡopPlaceholder
)

// ϡlookupOp translates an opcode to a string.
var ϡlookupOp = []string{
	ϡopExit: "exit", ϡopCall: "call", ϡopCallA: "callA",
	ϡopCallB: "callB", ϡopCumulOrF: "cumulOrF",
	ϡopJump: "jump", ϡopJumpIfF: "jumpIfF", ϡopJumpIfT: "jumpIfT",
	ϡopMatch: "match", ϡopNilIfF: "nilIfF", ϡopNilIfT: "nilIfT",
	ϡopPop: "pop", ϡopPopVJumpIfF: "popVJumpIfF",
	ϡopPush: "push", ϡopRestore: "restore", ϡopRestoreIfF: "restoreIfF",
	ϡopReturn: "return", ϡopStoreIfT: "storeIfT", ϡopTakeLOrJump: "takeLOrJump",
}

// String returns the string representation of the opcode.
func (op ϡop) String() string {
	if 0 <= op && int(op) < len(ϡlookupOp) {
		return ϡlookupOp[op]
	}
	return "ϡop(" + strconv.Itoa(int(op)) + ")"
}

// ϡinstr holds a single instruction: an opcode with its arguments.
type ϡinstr struct {
	op       ϡop
	ruleNmIx int // because bootstrap instructions have rule index -1
	args     []uint16
}

// String returns the string representation of the instruction.
func (ins ϡinstr) String() string {
	var buf bytes.Buffer

	buf.WriteString("{" + strconv.Itoa(int(ins.op)) + ", " +
		strconv.Itoa(int(ins.ruleNmIx)) + ", ")

	if len(ins.args) > 0 {
		buf.WriteString("[]uint16{")
		for i, arg := range ins.args {
			if i > 0 {
				buf.WriteString(", ")
			}
			buf.WriteString(strconv.Itoa(int(arg)))
		}
		buf.WriteString("}")
	} else {
		buf.WriteString("nil")
	}

	buf.WriteString("}")
	return buf.String()
}

//+pigeon: parser.go

// position records a position in the text. It is part of the supported
// API.
type position struct {
	// line is the 1-based index of the line of the current rune.
	line int
	// col is the 1-based index of the current rune on the line.
	col int
	// offset is the 0-based index of the starting byte of the current rune.
	offset int
}

// String formats a position as a string.
func (p position) String() string {
	return fmt.Sprintf("%d:%d (%d)", p.line, p.col, p.offset)
}

// current represents current matching data. It is the value on which
// action and predicate code blocks are generated as methods. It is
// part of the supported API.
type current struct {
	// pos holds the start position of the current match.
	pos position
	// text contains the raw text of the match. It is a slice in the
	// source data, so it should not be modified.
	text []byte
}

// ϡsvpt stores all state required to go back to a point in the
// parser.
type ϡsvpt struct {
	position
	rn rune
	w  int
}

// ϡparser parses the input text as rune code points.
type ϡparser struct {
	data []byte
	pt   ϡsvpt
	cur  current
}

// peek returns the current rune.
func (p *ϡparser) peek() rune {
	return p.pt.rn
}

// read advances the parser to the next rune.
func (p *ϡparser) read() {
	p.pt.offset += p.pt.w
	rn, n := utf8.DecodeRune(p.data[p.pt.offset:])
	p.pt.rn = rn
	p.pt.w = n

	if rn == utf8.RuneError {
		if n > 0 {
			panic(errInvalidEncoding)
		}
	} else {
		p.pt.col++
		if rn == '\n' {
			p.pt.line++
			p.pt.col = 0
		}
	}
}

// sliceFrom gets the slice of bytes from the start savepoint to
// the current position, non inclusive.
func (p *ϡparser) sliceFrom(start ϡsvpt) []byte {
	return p.data[start.position.offset:p.pt.position.offset]
}

//+pigeon: pub.go

// Option is a function that can set an option on the parser. It returns
// the previous setting as an Option.
type Option func(*ϡvm) Option

// Debug creates an Option to set the debug flag to b. When set to true,
// debugging information is printed to stdout while parsing.
//
// The default is false.
func Debug(b bool) Option {
	return func(v *ϡvm) Option {
		old := v.debug
		v.debug = b
		return Debug(old)
	}
}

// Memoize creates an Option to set the memoize flag to b. When set to true,
// the parser will cache all results so each expression is evaluated only
// once. This guarantees linear parsing time even for pathological cases,
// at the expense of more memory and slower times for typical cases.
//
// The default is false.
func Memoize(b bool) Option {
	return func(v *ϡvm) Option {
		old := v.memoize
		v.memoize = b
		return Memoize(old)
	}
}

// Recover creates an Option to set the recover flag to b. When set to
// true, this causes the parser to recover from panics and convert it
// to an error. Setting it to false can be useful while debugging to
// access the full stack trace.
//
// The default is true.
func Recover(b bool) Option {
	return func(v *ϡvm) Option {
		old := v.recover
		v.recover = b
		return Recover(old)
	}
}

// ParseFile parses the file identified by filename.
func ParseFile(filename string, opts ...Option) (interface{}, error) {
	f, err := os.Open(filename)
	if err != nil {
		return nil, err
	}
	defer f.Close()
	return ParseReader(filename, f, opts...)
}

// ParseReader parses the data from r using filename as information in the
// error messages.
func ParseReader(filename string, r io.Reader, opts ...Option) (interface{}, error) {
	b, err := ioutil.ReadAll(r)
	if err != nil {
		return nil, err
	}

	return Parse(filename, b, opts...)
}

// Parse parses the data from b using filename as information in the
// error messages.
func Parse(filename string, b []byte, opts ...Option) (interface{}, error) {
	p := &ϡparser{
		data: b,
		pt:   ϡsvpt{position: position{line: 1}},
	}
	v := &ϡvm{
		filename: filename,
		parser:   p,
		recover:  true,
	}
	return v.setOptions(opts).run(ϡtheProgram)
}

//+pigeon: stacks.go

// ϡpstack implements the Position stack. It stores savepoints.
type ϡpstack struct {
	ar []ϡsvpt
	sp int
}

// push adds a value on the stack.
func (p *ϡpstack) push(pt ϡsvpt) {
	if p.sp >= len(p.ar) {
		p.ar = append(p.ar, pt)
	} else {
		p.ar[p.sp] = pt
	}
	p.sp++
}

// pop removes a value from the stack.
func (p *ϡpstack) pop() ϡsvpt {
	p.sp--
	return p.ar[p.sp]
}

func (p *ϡpstack) len() int {
	return p.sp
}

func newPstack(cap int) *ϡpstack {
	return &ϡpstack{ar: make([]ϡsvpt, cap)}
}

// ϡistack implements the Instruction index stack. It stores integers.
type ϡistack struct {
	ar []uint16
	sp int
}

// push adds a value on the stack.
func (i *ϡistack) push(v uint16) {
	if i.sp >= len(i.ar) {
		i.ar = append(i.ar, v)
	} else {
		i.ar[i.sp] = v
	}
	i.sp++
}

// pop removes a value from the stack.
func (i *ϡistack) pop() uint16 {
	i.sp--
	return i.ar[i.sp]
}

func (i *ϡistack) len() int {
	return i.sp
}

func newIstack(cap int) *ϡistack {
	return &ϡistack{ar: make([]uint16, cap)}
}

// ϡvstack implements the Value stack. It stores empty interfaces.
type ϡvstack struct {
	ar []interface{}
	sp int
}

// push adds a value on the stack.
func (v *ϡvstack) push(i interface{}) {
	if v.sp >= len(v.ar) {
		v.ar = append(v.ar, i)
	} else {
		v.ar[v.sp] = i
	}
	v.sp++
}

// pop removes a value from the stack.
func (v *ϡvstack) pop() interface{} {
	v.sp--
	return v.ar[v.sp]
}

// peek returns the value at the top of the stack, leaving it there.
func (v *ϡvstack) peek() interface{} {
	return v.ar[v.sp-1]
}

func (v *ϡvstack) len() int {
	return v.sp
}

func newVstack(cap int) *ϡvstack {
	return &ϡvstack{ar: make([]interface{}, cap)}
}

// ϡlstack implements the Loop stack. It stores slices of integers.
type ϡlstack struct {
	ar [][]uint16
	sp int
}

// push adds a value on the stack.
func (l *ϡlstack) push(a []uint16) {
	if l.sp >= len(l.ar) {
		l.ar = append(l.ar, a)
	} else {
		l.ar[l.sp] = a
	}
	l.sp++
}

// pop removes a value from the stack.
func (l *ϡlstack) pop() []uint16 {
	l.sp--
	return l.ar[l.sp]
}

// take removes the integer at index 0 from the slice at the top of the
// stack. It returns -1 if the slice is empty. The slice is left on the
// stack.
func (l *ϡlstack) take() int {
	v := -1
	a := l.ar[l.sp-1]
	if len(a) > 0 {
		v = int(a[0])
		l.ar[l.sp-1] = a[1:]
	}
	return v
}

func (l *ϡlstack) len() int {
	return l.sp
}

func newLstack(cap int) *ϡlstack {
	return &ϡlstack{ar: make([][]uint16, cap)}
}

// ϡargsSet holds the list of arguments (key and value) to pass
// to the code blocks.
type ϡargsSet map[string]interface{}

// ϡastack is a stack of ϡargsSet.
type ϡastack struct {
	ar []ϡargsSet
	sp int
}

// push adds an empty ϡargsSet on top of the stack.
func (a *ϡastack) push() {
	if a.sp >= len(a.ar) {
		a.ar = append(a.ar, nil)
	} else {
		a.ar[a.sp] = nil
	}
	a.sp++
}

// pop removes the top ϡargsSet from the stack.
func (a *ϡastack) pop() {
	a.sp--
}

// peek returns the current top ϡargsSet.
func (a *ϡastack) peek() ϡargsSet {
	as := a.ar[a.sp-1]
	if as == nil {
		as = make(ϡargsSet)
		a.ar[a.sp-1] = as
	}
	return as
}

func (a *ϡastack) len() int {
	return a.sp
}

func newAstack(cap int) *ϡastack {
	return &ϡastack{ar: make([]ϡargsSet, cap)}
}

//+pigeon: vm.go

// ϡsentinel is a type used to define sentinel values that shouldn't
// be equal to something else.
type ϡsentinel int

const (
	// ϡmatchFailed is a sentinel value used to indicate a match failure.
	ϡmatchFailed ϡsentinel = iota - 1
)

const (
	// stack IDs, used in PUSH and POP's first argument
	ϡpstackID = iota + 1
	ϡlstackID
	ϡvstackID
	ϡistackID
	ϡastackID

	// special V stack values
	ϡvValNil    uint16 = 0
	ϡvValFailed uint16 = 1
	ϡvValEmpty  uint16 = 2
)

var (
	ϡstackNm = []string{
		ϡpstackID: "P",
		ϡlstackID: "L",
		ϡvstackID: "V",
		ϡistackID: "I",
		ϡastackID: "A",
	}
)

// special values that may be pushed on the V stack.
var ϡvSpecialValues = []interface{}{
	nil,
	ϡmatchFailed,
	[]interface{}(nil),
}

// ϡmemoizedResult holds the state required to reuse a memoized result.
type ϡmemoizedResult struct {
	v  interface{}
	pt ϡsvpt
}

// ϡffp holds state to record the farthest failure position.
type ϡffp struct {
	pos      position
	ruleNmIx int
	got      []byte
	want     string
}

// err returns an error if a farthest failure position has been recorded,
// nil otherwise.
func (ffp ϡffp) err() error {
	if ffp.pos.offset >= 0 {
		return ffp
	}
	return nil
}

// Error implements the error interface.
func (ffp ϡffp) Error() string {
	return fmt.Sprintf("expected %s, got %s", ffp.want, strconv.Quote(string(ffp.got)))
}

// ϡprogram is the data structure that is generated by the builder
// based on an input PEG. It contains the program information required
// to execute the grammar using the vm.
type ϡprogram struct {
	instrs []ϡinstr

	// lists
	ms []ϡmatcher
	as []func(*ϡvm) (interface{}, error)
	bs []func(*ϡvm) (bool, error)
	ss []string
}

// String formats the program's instructions in a human-readable format.
func (pg ϡprogram) String() string {
	var buf bytes.Buffer

	for i, instr := range pg.instrs {
		buf.WriteString(fmt.Sprintf("[%3d]: %s\n", i, pg.instrToString(instr)))
	}
	return buf.String()
}

// instrToString formats an instruction in a human-readable format, in the
// context of the program.
func (pg ϡprogram) instrToString(instr ϡinstr) string {
	var buf bytes.Buffer

	rule := pg.ruleNameAt(instr.ruleNmIx)
	if rule == "" {
		rule = "<bootstrap>"
	}
	buf.WriteString(fmt.Sprintf("%s.%s %v", rule, instr.op, instr.args))
	switch instr.op {
	case ϡopPush, ϡopPop:
		buf.WriteString(" " + ϡstackNm[instr.args[0]])
	case ϡopMatch:
		buf.WriteString(fmt.Sprintf(" %s", pg.ms[instr.args[0]]))
	case ϡopStoreIfT:
		buf.WriteString(" " + pg.ss[instr.args[0]])
	}
	return buf.String()
}

// ruleNameAt returns the name of the rule that contains the instruction
// index. It returns an empty string is the instruction is not part of a
// rule (bootstrap instruction, invalid index).
func (pg ϡprogram) ruleNameAt(ix int) string {
	if ix < 0 || ix >= len(pg.ss) {
		return ""
	}
	return pg.ss[ix]
}

// ϡvm holds the state to execute a compiled grammar.
type ϡvm struct {
	// input
	filename string
	parser   *ϡparser

	// options
	debug   bool
	memoize bool
	recover bool

	// program data
	pc  uint16
	pg  *ϡprogram
	cur current

	// stacks
	p *ϡpstack
	l *ϡlstack
	v *ϡvstack
	i *ϡistack
	a *ϡastack

	// memoized results: by instruction index, then by byte offset
	memo map[uint16]map[int]ϡmemoizedResult
	ffp  ϡffp

	// stats
	matchCnt    int
	callCnt     int
	actionCnt   int
	codePredCnt int

	// error list
	errs errList
}

func (v *ϡvm) fromMemo(ix uint16, pt ϡsvpt) bool {
	if v.memo == nil {
		return false
	}
	m := v.memo[ix]
	if m == nil {
		return false
	}
	result, ok := m[pt.offset]
	if ok {
		v.parser.pt = result.pt
		v.v.push(result.v)
		return true
	}
	return false
}

func (v *ϡvm) memoizeMatch(ix uint16, pt ϡsvpt, match bool) {
	if v.memo == nil {
		v.memo = make(map[uint16]map[int]ϡmemoizedResult)
	}
	m, ok := v.memo[ix]
	if !ok {
		m = make(map[int]ϡmemoizedResult)
		v.memo[ix] = m
	}

	if match {
		m[pt.offset] = ϡmemoizedResult{v.parser.sliceFrom(pt), v.parser.pt}
		return
	}
	m[pt.offset] = ϡmemoizedResult{ϡmatchFailed, pt}
}

// setOptions applies the options in sequence on the vm. It returns the
// vm to allow for chaining calls.
func (v *ϡvm) setOptions(opts []Option) *ϡvm {
	for _, opt := range opts {
		opt(v)
	}
	return v
}

// addErr adds the error at the current parser position, without rule name
// information.
func (v *ϡvm) addErr(err error) {
	v.addErrAt(err, -1, v.parser.pt.position)
}

// addErrAt adds the error at the specified position, for the rule name at
// ruleNmIx.
func (v *ϡvm) addErrAt(err error, ruleNmIx int, pos position) {
	var buf bytes.Buffer
	if v.filename != "" {
		buf.WriteString(v.filename)
	}
	if buf.Len() > 0 {
		buf.WriteString(":")
	}
	buf.WriteString(fmt.Sprintf("%s", pos))

	ruleNm := v.pg.ruleNameAt(ruleNmIx)
	if ruleNm != "" {
		buf.WriteString(": ")
		buf.WriteString("rule " + ruleNm)
	}

	pe := &parserError{Inner: err, ϡprefix: buf.String()}
	v.errs.ϡadd(pe)
}

// dumpSnapshot writes a dump of the current VM state to w.
func (v *ϡvm) dumpSnapshot(w io.Writer) {
	var buf bytes.Buffer

	if v.filename != "" {
		buf.WriteString(v.filename + ":")
	}
	buf.WriteString(fmt.Sprintf("%s: %#U\n", v.parser.pt.position, v.parser.pt.rn))

	// write the next 5 instructions
	ix := v.pc - 1
	if ix > 0 {
		ix--
	}
	stdFmt := ". [%d]: %s"
	for i := 0; i < 5; i++ {
		stdFmt := stdFmt
		if ix == v.pc-1 {
			stdFmt = ">" + stdFmt[1:]
		}
		instr := v.pg.instrs[ix]
		switch instr.op {
		case ϡopCall:
			buf.WriteString(fmt.Sprintf(stdFmt+"\n", ix, v.pg.instrToString(instr)))
			ix = v.i.pop() // continue with instructions at this index
			v.i.push(ix)
			continue
		default:
			buf.WriteString(fmt.Sprintf(stdFmt+"\n", ix, v.pg.instrToString(instr)))
		}
		ix++
		if int(ix) >= len(v.pg.instrs) {
			break
		}
	}

	// // print the stacks
	// buf.WriteString("[ P: ")
	// for i := 0; i < 3; i++ {
	// 	if len(v.p) <= i {
	// 		break
	// 	}
	// 	if i > 0 {
	// 		buf.WriteString(", ")
	// 	}
	// 	val := v.p[len(v.p)-i-1]
	// 	buf.WriteString(fmt.Sprintf("\"%v\"", val))
	// }
	// buf.WriteString(" ]\n[ V: ")
	// for i := 0; i < 3; i++ {
	// 	if len(v.v) <= i {
	// 		break
	// 	}
	// 	if i > 0 {
	// 		buf.WriteString(", ")
	// 	}
	// 	val := v.v[len(v.v)-i-1]
	// 	buf.WriteString(fmt.Sprintf("%#v", val))
	// }
	// buf.WriteString(" ]\n[ I: ")
	// for i := 0; i < 3; i++ {
	// 	if len(v.i) <= i {
	// 		break
	// 	}
	// 	if i > 0 {
	// 		buf.WriteString(", ")
	// 	}
	// 	val := v.i[len(v.i)-i-1]
	// 	buf.WriteString(fmt.Sprintf("%d", val))
	// }
	// buf.WriteString(" ]\n[ L: ")
	// for i := 0; i < 3; i++ {
	// 	if len(v.l) <= i {
	// 		break
	// 	}
	// 	if i > 0 {
	// 		buf.WriteString(", ")
	// 	}
	// 	val := v.l[len(v.l)-i-1]
	// 	buf.WriteString(fmt.Sprintf("%v", val))
	// }
	// buf.WriteString(" ]\n")
	fmt.Fprintln(w, buf.String())
}

// run executes the provided program in this VM, and returns the result.
func (v *ϡvm) run(pg *ϡprogram) (interface{}, error) {
	v.pg = pg
	v.a = newAstack(128)
	v.i = newIstack(128)
	v.v = newVstack(128)
	v.l = newLstack(128)
	v.p = newPstack(128)
	v.ffp.pos.offset = -1
	ret := v.dispatch()

	// if the match failed, translate that to a nil result and make
	// sure it returns an error
	if ret == ϡmatchFailed {
		ret = nil
		if len(v.errs) == 0 {
			if err := v.ffp.err(); err != nil {
				v.addErrAt(err, v.ffp.ruleNmIx, v.ffp.pos)
			} else {
				v.addErr(errNoMatch)
			}
		}
	}

	return ret, v.errs.ϡerr()
}

// dispatch is the proper execution method of the VM, it loops over
// the instructions and executes each opcode.
func (v *ϡvm) dispatch() interface{} {
	var instrPath []uint16
	if v.debug {
		fmt.Fprintln(os.Stderr, v.pg)
		defer func() {
			var buf bytes.Buffer

			buf.WriteString("Execution path:\n")
			for _, ix := range instrPath {
				buf.WriteString(fmt.Sprintf("[%3d]: %s\n", ix, v.pg.instrToString(v.pg.instrs[ix])))
			}
			fmt.Fprintln(os.Stderr, buf.String())
		}()
	}

	if v.recover {
		// if recover is set, recover from panics and convert to error.
		defer func() {
			if e := recover(); e != nil {
				ruleIx := -1
				if v.pc > 0 {
					ruleIx = v.pg.instrs[v.pc-1].ruleNmIx
				}
				switch e := e.(type) {
				case error:
					v.addErrAt(e, ruleIx, v.parser.pt.position)
				default:
					v.addErrAt(fmt.Errorf("%v", e), ruleIx, v.parser.pt.position)
				}
			}
		}()
	}

	// move to first rune before starting the loop
	v.parser.read()
	for {
		// fetch and decode the instruction
		instr := v.pg.instrs[v.pc]
		instrPath = append(instrPath, v.pc)

		// increment program counter
		v.pc++

		switch instr.op {
		case ϡopCall:
			if v.debug {
				v.dumpSnapshot(os.Stderr)
			}
			ix := v.i.pop()
			v.i.push(v.pc)
			v.pc = ix
			v.callCnt++

		case ϡopCallA:
			if v.debug {
				v.dumpSnapshot(os.Stderr)
			}
			v.v.pop()
			start := v.p.pop()
			v.cur.pos = start.position
			v.cur.text = v.parser.sliceFrom(start)
			if int(instr.args[0]) >= len(v.pg.as) {
				panic(fmt.Sprintf("invalid %s argument: %d", instr.op, instr.args[0]))
			}
			fn := v.pg.as[instr.args[0]]
			val, err := fn(v)
			if err != nil {
				v.addErrAt(err, int(instr.ruleNmIx), start.position)
			}
			v.v.push(val)
			v.actionCnt++

		case ϡopCallB:
			if v.debug {
				v.dumpSnapshot(os.Stderr)
			}
			v.cur.pos = v.parser.pt.position
			v.cur.text = nil
			if int(instr.args[0]) >= len(v.pg.bs) {
				panic(fmt.Sprintf("invalid %s argument: %d", instr.op, instr.args[0]))
			}
			fn := v.pg.bs[instr.args[0]]
			val, err := fn(v)
			if err != nil {
				v.addErrAt(err, int(instr.ruleNmIx), v.parser.pt.position)
			}
			v.codePredCnt++
			if !val {
				v.v.push(ϡmatchFailed)
				break
			}
			v.v.push(nil)

		case ϡopCumulOrF:
			va, vb := v.v.pop(), v.v.pop()
			if va == ϡmatchFailed {
				v.v.push(ϡmatchFailed)
				break
			}
			switch vb := vb.(type) {
			case []interface{}:
				vb = append(vb, va)
				v.v.push(vb)
			case ϡsentinel:
				v.v.push([]interface{}{va})
			default:
				panic(fmt.Sprintf("invalid %s value type on the V stack: %T", instr.op, vb))
			}

		case ϡopExit:
			return v.v.pop()

		case ϡopJump:
			v.pc = instr.args[0]

		case ϡopJumpIfF:
			if top := v.v.peek(); top == ϡmatchFailed {
				v.pc = instr.args[0]
			}

		case ϡopJumpIfT:
			if top := v.v.peek(); top != ϡmatchFailed {
				v.pc = instr.args[0]
			}

		case ϡopMatch:
			start := v.parser.pt
			if v.memoize && v.fromMemo(v.pc-1, start) {
				break
			}

			if int(instr.args[0]) >= len(v.pg.ms) {
				panic(fmt.Sprintf("invalid %s argument: %d", instr.op, instr.args[0]))
			}
			m := v.pg.ms[instr.args[0]]
			ok := m.match(v.parser)
			if v.memoize {
				v.memoizeMatch(v.pc-1, start, ok)
			}
			v.matchCnt++
			if ok {
				v.v.push(v.parser.sliceFrom(start))
				break
			}
			// did not match, record ffp if this is the farthest failure
			if start.offset > v.ffp.pos.offset {
				v.ffp.pos = start.position
				v.ffp.got = v.parser.sliceFrom(start)
				v.ffp.ruleNmIx = instr.ruleNmIx
				v.ffp.want = m.toDisplayMsg()
			}
			v.v.push(ϡmatchFailed)
			v.parser.pt = start

			if v.debug {
				v.dumpSnapshot(os.Stderr)
			}

		case ϡopNilIfF:
			if top := v.v.pop(); top == ϡmatchFailed {
				v.v.push(nil)
				break
			}
			v.v.push(ϡmatchFailed)

		case ϡopNilIfT:
			if top := v.v.pop(); top != ϡmatchFailed {
				v.v.push(nil)
				break
			}
			v.v.push(ϡmatchFailed)

		case ϡopPop:
			switch instr.args[0] {
			case ϡlstackID:
				v.l.pop()
			case ϡpstackID:
				v.p.pop()
			case ϡastackID:
				v.a.pop()
			case ϡvstackID:
				v.v.pop()
			default:
				panic(fmt.Sprintf("invalid %s argument: %d", instr.op, instr.args[0]))
			}

		case ϡopPopVJumpIfF:
			if top := v.v.peek(); top == ϡmatchFailed {
				v.v.pop()
				v.pc = instr.args[0]
			}

		case ϡopPush:
			switch instr.args[0] {
			case ϡpstackID:
				v.p.push(v.parser.pt)
			case ϡistackID:
				v.i.push(instr.args[1])
			case ϡvstackID:
				if int(instr.args[1]) >= len(ϡvSpecialValues) {
					panic(fmt.Sprintf("invalid %s V stack argument: %d", instr.op, instr.args[1]))
				}
				v.v.push(ϡvSpecialValues[instr.args[1]])
			case ϡastackID:
				v.a.push()
			case ϡlstackID:
				v.l.push(instr.args[1:])
			default:
				panic(fmt.Sprintf("invalid %s argument: %d", instr.op, instr.args[0]))
			}

		case ϡopRestore:
			pt := v.p.pop()
			v.parser.pt = pt

		case ϡopRestoreIfF:
			pt := v.p.pop()
			if top := v.v.peek(); top == ϡmatchFailed {
				v.parser.pt = pt
			}

		case ϡopReturn:
			ix := v.i.pop()
			v.pc = ix

		case ϡopStoreIfT:
			if top := v.v.peek(); top != ϡmatchFailed {
				// get the label name
				if int(instr.args[0]) >= len(v.pg.ss) {
					panic(fmt.Sprintf("invalid %s argument: %d", instr.op, instr.args[0]))
				}
				lbl := v.pg.ss[instr.args[0]]

				// store the value
				as := v.a.peek()
				as[lbl] = top
			}

		case ϡopTakeLOrJump:
			ix := v.l.take()
			if ix < 0 {
				v.pc = instr.args[0]
				break
			}
			v.i.push(uint16(ix))

		default:
			panic(fmt.Sprintf("unknown opcode %s", instr.op))
		}
	}
}
